"""Reusable helpers for notebooks C01-C07.

The first seven notebooks build the system layers used by the Framework:
climate, hydrology, water quality, ONI, hydraulic reserves, perception and
governance. This module keeps their repeated validation and inventory logic in
one place so notebooks can focus on exploration while scripts and the
Streamlit app reuse the same business anatomy.
"""

from __future__ import annotations

import json
from pathlib import Path

import pandas as pd

from framework_v7.catalog import LAYER_CATALOG
from framework_v7.layers import LAYER_MODULES
from framework_v7.paths import BASE_DIR, DATA_DIR, NOTEBOOKS_DIR, rel
from framework_v7.profiling import dataset_profile, missing_profile

from .utils import artifact_inventory


LAYER_NOTEBOOK_FOLDERS = {
    "C01 - Climatica": "C01_CLIMATICA",
    "C02 - Hidrologica": "C02_HIDROLOGICA",
    "C03 - Calidad de agua": "C03_CALIDAD_AGUA",
    "C04 - ONI": "C04_ONI",
    "C05 - Hidraulica": "C05_HIDRAULICA",
    "C06 - Percepcion": "C06_PERCEPCION",
    "C07 - Gobernanza": "C07_GOBERNANZA",
}

RAW_LAYER_FOLDERS = {
    "C01 - Climatica": "C01",
    "C02 - Hidrologica": "C02",
    "C03 - Calidad de agua": "C03",
    "C04 - ONI": "C04",
    "C05 - Hidraulica": "C05",
    "C06 - Percepcion": "C06",
    "C07 - Gobernanza": "C07",
}


def notebook_folder(layer_name: str) -> Path:
    """Return the notebook folder associated with a layer.

    Args:
        layer_name: Canonical layer name registered in ``LAYER_CATALOG``.

    Returns:
        Path to the notebook folder for the requested layer.

    Raises:
        KeyError: If the layer does not have a registered notebook folder.
    """

    return NOTEBOOKS_DIR / LAYER_NOTEBOOK_FOLDERS[layer_name]


def raw_folder(layer_name: str) -> Path:
    """Return the raw-data folder associated with a layer.

    Args:
        layer_name: Canonical layer name registered in ``LAYER_CATALOG``.

    Returns:
        Path to the raw artifact folder for the requested layer.

    Raises:
        KeyError: If the layer does not have a registered raw folder.
    """

    return DATA_DIR / "RAW" / RAW_LAYER_FOLDERS[layer_name]


def master_folder(layer_name: str) -> Path:
    """Return the master artifact folder associated with a layer.

    Args:
        layer_name: Canonical layer name registered in ``LAYER_CATALOG``.

    Returns:
        Path where the layer stores curated master artifacts.
    """

    return LAYER_CATALOG[layer_name]["folder"]


def notebook_inventory(layer_name: str | None = None) -> pd.DataFrame:
    """Build an inventory of notebooks used by C01-C07.

    Args:
        layer_name: Optional layer name used to restrict the inventory. When
            ``None``, all C01-C07 folders are scanned.

    Returns:
        DataFrame with notebook path, code cell count, markdown cell count,
        code-line count and file size in kilobytes.
    """

    layer_names = [layer_name] if layer_name else list(LAYER_NOTEBOOK_FOLDERS)
    rows = []
    for current_layer in layer_names:
        folder = notebook_folder(current_layer)
        for notebook_path in sorted(folder.glob("*.ipynb")):
            notebook = json.loads(notebook_path.read_text(encoding="utf-8"))
            cells = notebook.get("cells", [])
            code_cells = [cell for cell in cells if cell.get("cell_type") == "code"]
            markdown_cells = [cell for cell in cells if cell.get("cell_type") == "markdown"]
            rows.append(
                {
                    "Capa": current_layer,
                    "Notebook": notebook_path.name,
                    "Ruta": rel(notebook_path),
                    "Celdas_Codigo": len(code_cells),
                    "Celdas_Markdown": len(markdown_cells),
                    "Lineas_Codigo": sum(len(cell.get("source", [])) for cell in code_cells),
                    "Tamano_KB": round(notebook_path.stat().st_size / 1024, 1),
                }
            )
    return pd.DataFrame(rows)


def layer_artifact_inventory(layer_name: str | None = None) -> pd.DataFrame:
    """Inventory raw and master artifacts generated by C01-C07.

    Args:
        layer_name: Optional layer name used to restrict the inventory. When
            ``None``, all C01-C07 layers are scanned.

    Returns:
        DataFrame with layer, artifact zone, relative file path, format and
        size in bytes.
    """

    layer_names = [layer_name] if layer_name else list(LAYER_CATALOG)
    frames = []
    for current_layer in layer_names:
        for zone, folder in [
            ("RAW", raw_folder(current_layer)),
            ("MASTER", master_folder(current_layer)),
        ]:
            inventory = artifact_inventory(folder)
            if inventory.empty:
                continue
            inventory = inventory.rename(columns={"Experimento": "Grupo"})
            inventory.insert(0, "Capa", current_layer)
            inventory.insert(1, "Zona", zone)
            inventory["Archivo"] = inventory["Archivo"].apply(
                lambda value, root=folder: rel(root / str(value))
            )
            frames.append(inventory)
    return pd.concat(frames, ignore_index=True) if frames else pd.DataFrame()


def layer_quality_summary() -> pd.DataFrame:
    """Summarize quality and availability for the curated C01-C07 layers.

    Returns:
        DataFrame with one row per layer, including dataset dimensions, nulls,
        duplicates, numeric-variable count and detected key-variable count.
    """

    rows = []
    for layer_name, layer_module in LAYER_MODULES.items():
        dataset = layer_module.load_dataset()
        profile = dataset_profile(dataset)
        key_variables = layer_module.available_key_variables()
        config = LAYER_CATALOG[layer_name]
        main_path = config["folder"] / config["main"]
        rows.append(
            {
                "Capa": layer_name,
                "Rol_Sistemico": config["role"],
                "Archivo_Principal": rel(main_path),
                "Disponible": main_path.exists(),
                "Filas": profile["filas"],
                "Columnas": profile["columnas"],
                "Nulos": profile["nulos"],
                "Duplicados": profile["duplicados"],
                "Variables_Numericas": profile["numericas"],
                "Variables_Clave": len(key_variables),
            }
        )
    return pd.DataFrame(rows)


def layer_missing_summary(layer_name: str, limit: int = 10) -> pd.DataFrame:
    """Return the top missing-value variables for a layer.

    Args:
        layer_name: Canonical layer name registered in ``LAYER_MODULES``.
        limit: Maximum number of variables to return.

    Returns:
        DataFrame with variable name, null count and coverage percentage.
    """

    dataset = LAYER_MODULES[layer_name].load_dataset()
    summary = missing_profile(dataset, limit=limit)
    if summary.empty:
        return summary
    summary.insert(0, "Capa", layer_name)
    return summary


def layer_execution_summary() -> pd.DataFrame:
    """Build an execution-oriented summary for notebooks C01-C07.

    Returns:
        DataFrame that connects each layer with notebook count, raw artifact
        count, master artifact count and curated dataset dimensions.
    """

    notebooks = notebook_inventory()
    artifacts = layer_artifact_inventory()
    quality = layer_quality_summary()
    rows = []
    for layer_name in LAYER_CATALOG:
        notebook_count = len(notebooks[notebooks["Capa"] == layer_name]) if not notebooks.empty else 0
        raw_count = 0
        master_count = 0
        if not artifacts.empty:
            layer_artifacts = artifacts[artifacts["Capa"] == layer_name]
            raw_count = int((layer_artifacts["Zona"] == "RAW").sum())
            master_count = int((layer_artifacts["Zona"] == "MASTER").sum())
        quality_row = quality[quality["Capa"] == layer_name].iloc[0].to_dict()
        rows.append(
            {
                "Capa": layer_name,
                "Notebooks": notebook_count,
                "Artefactos_RAW": raw_count,
                "Artefactos_MASTER": master_count,
                "Filas": quality_row["Filas"],
                "Columnas": quality_row["Columnas"],
                "Nulos": quality_row["Nulos"],
                "Variables_Clave": quality_row["Variables_Clave"],
                "Disponible": quality_row["Disponible"],
            }
        )
    return pd.DataFrame(rows)


def export_layer_reports(output_dir: Path | None = None) -> list[Path]:
    """Export reusable C01-C07 reports as CSV files.

    Args:
        output_dir: Destination folder. When ``None``, reports are written to
            ``DATA/MASTER/CAPAS_RESUMEN``.

    Returns:
        List of CSV paths written by the function.
    """

    destination = output_dir or BASE_DIR / "DATA" / "MASTER" / "CAPAS_RESUMEN"
    destination.mkdir(parents=True, exist_ok=True)
    reports = {
        "inventario_notebooks_capas.csv": notebook_inventory(),
        "inventario_artefactos_capas.csv": layer_artifact_inventory(),
        "resumen_calidad_capas.csv": layer_quality_summary(),
        "resumen_ejecucion_capas.csv": layer_execution_summary(),
    }
    written = []
    for file_name, report in reports.items():
        path = destination / file_name
        report.to_csv(path, index=False)
        written.append(path)
    return written
