"""Data loading functions for FRAMEWORK V7.

The Streamlit app reads several CSV and Excel artifacts generated by the
notebooks. This module keeps all IO code in one place and caches expensive
loads through Streamlit, while returning plain pandas DataFrames to the view
layer.
"""

from __future__ import annotations

from dataclasses import dataclass
from functools import lru_cache
from pathlib import Path

import pandas as pd

from .catalog import EXPERIMENT_DESIGN_FILES
from .paths import (
    COVERAGE_PATH,
    DIAGNOSTIC_PATH,
    MASTER_PATH,
    METADATA_PATH,
    ML_DATASET_PATH,
    MODEL_DIAGNOSTIC_PATH,
    MODEL_RECOMMENDATIONS_PATH,
    PREDICTIONS_PATH,
)


@dataclass(frozen=True)
class ProjectData:
    """Container with datasets required by the dashboard.

    Attributes:
        metadata: Experiment metadata table.
        predictions: Prediction outputs for Exp01.
        ml_dataset: Transformed machine learning dataset.
        diagnostic: Statistical diagnostic table.
        master: Master dataset with imputations.
        coverage: Precomputed variable coverage report.
        experiment_design: Design datasets keyed by artifact label.
        model_diagnostic: Exp01 model diagnostic table.
        model_recommendations: Exp01 recommendation table.
        meta: Metadata as a key-value dictionary.
    """

    metadata: pd.DataFrame
    predictions: pd.DataFrame
    ml_dataset: pd.DataFrame
    diagnostic: pd.DataFrame
    master: pd.DataFrame
    coverage: pd.DataFrame
    experiment_design: dict[str, pd.DataFrame]
    model_diagnostic: pd.DataFrame
    model_recommendations: pd.DataFrame
    meta: dict[str, str]


@lru_cache(maxsize=None)
def load_csv(path: Path) -> pd.DataFrame:
    """Load a CSV file as a DataFrame.

    Args:
        path: Path to the CSV artifact.

    Returns:
        A pandas DataFrame. Returns an empty DataFrame when the file is absent.
    """

    if not path.exists():
        return pd.DataFrame()
    return pd.read_csv(path)


@lru_cache(maxsize=None)
def load_excel(path: Path) -> pd.DataFrame:
    """Load an Excel file as a DataFrame.

    Args:
        path: Path to the Excel artifact.

    Returns:
        A pandas DataFrame. Returns an empty DataFrame when the file is absent.
    """

    if not path.exists():
        return pd.DataFrame()
    return pd.read_excel(path)


@lru_cache(maxsize=None)
def read_text(path: Path) -> str:
    """Read a text artifact safely.

    Args:
        path: Path to a markdown, text or README file.

    Returns:
        File content as UTF-8 text. Returns an empty string when absent.
    """

    if not path.exists():
        return ""
    return path.read_text(encoding="utf-8", errors="ignore")


def metadata_dict(df: pd.DataFrame) -> dict[str, str]:
    """Convert the metadata table into a dictionary.

    Args:
        df: Metadata DataFrame with ``Parametro`` and ``Valor`` columns.

    Returns:
        Dictionary mapping metadata parameter names to values.
    """

    if {"Parametro", "Valor"}.issubset(df.columns):
        return dict(zip(df["Parametro"].astype(str), df["Valor"].astype(str)))
    return {}


def load_project_data() -> ProjectData:
    """Load every dataset needed by the dashboard.

    Returns:
        ProjectData instance with raw DataFrames and parsed metadata.
    """

    metadata = load_csv(METADATA_PATH)
    experiment_design = {label: load_csv(path) for label, path in EXPERIMENT_DESIGN_FILES.items()}
    return ProjectData(
        metadata=metadata,
        predictions=load_csv(PREDICTIONS_PATH),
        ml_dataset=load_csv(ML_DATASET_PATH),
        diagnostic=load_csv(DIAGNOSTIC_PATH),
        master=load_csv(MASTER_PATH),
        coverage=load_csv(COVERAGE_PATH),
        experiment_design=experiment_design,
        model_diagnostic=load_csv(MODEL_DIAGNOSTIC_PATH),
        model_recommendations=load_csv(MODEL_RECOMMENDATIONS_PATH),
        meta=metadata_dict(metadata),
    )
