# **FRAMEWORK V7 DATASET MAESTRO**

## **M0 Configuración**

In [3]:
import pandas as pd
import numpy as np
import hashlib
from functools import reduce

# ============================================================
# FRAMEWORK V7
# DATASET MAESTRO
# ============================================================

NOMBRE_DATASET = "Dataset Maestro"

VERSION = "1.0"

RESPONSABLE = "Juan Carlos Riatiga"

URL_CLIMATICA = "https://raw.githubusercontent.com/jriatiga/FRAMEWORK_V7/refs/heads/main/DATA/MASTER/C01_MASTER/02_Capa_Climatica_Framework.xlsx"

URL_HIDROLOGICA = "https://raw.githubusercontent.com/jriatiga/FRAMEWORK_V7/refs/heads/main/DATA/MASTER/C02_MASTER/02_Capa_Hidrologica_Framework.xlsx"

URL_CALIDAD = "https://raw.githubusercontent.com/jriatiga/FRAMEWORK_V7/refs/heads/main/DATA/MASTER/C03_MASTER/02_Capa_Calidad_Agua_Framework.xlsx"

URL_ONI = "https://raw.githubusercontent.com/jriatiga/FRAMEWORK_V7/refs/heads/main/DATA/MASTER/C04_MASTER/02_Capa_ONI_Framework.xlsx"

URL_HIDRAULICA = "https://raw.githubusercontent.com/jriatiga/FRAMEWORK_V7/refs/heads/main/DATA/MASTER/C05_MASTER/02_Capa_Hidraulica_Framework.xlsx"

URL_PERCEPCION = "https://raw.githubusercontent.com/jriatiga/FRAMEWORK_V7/refs/heads/main/DATA/MASTER/C06_MASTER/02_Capa_Percepcion_Framework.xlsx"

URL_GOBERNANZA = "https://raw.githubusercontent.com/jriatiga/FRAMEWORK_V7/refs/heads/main/DATA/MASTER/CO7_MASTER/02_Capa_Gobernanza_Framework.xlsx"

## **M1 Descubrimiento Automático de Capas**

In [4]:
climatica = pd.read_excel(URL_CLIMATICA)

hidrologica = pd.read_excel(URL_HIDROLOGICA)

calidad = pd.read_excel(URL_CALIDAD)

oni = pd.read_excel(URL_ONI)

hidraulica = pd.read_excel(URL_HIDRAULICA)

percepcion = pd.read_excel(URL_PERCEPCION)

gobernanza = pd.read_excel(URL_GOBERNANZA)

## **M2 Validación de Capas**

In [5]:
# ============================================================
# M2 - VALIDACIÓN ESTRUCTURAL
# DATASET MAESTRO
# ============================================================

print("="*70)
print("M2 - VALIDACIÓN ESTRUCTURAL")
print("="*70)

capas = {
    "Climática": climatica,
    "Hidrológica": hidrologica,
    "Calidad del Agua": calidad,
    "ONI": oni,
    "Hidráulica": hidraulica,
    "Percepción": percepcion,
    "Gobernanza": gobernanza
}

for nombre, df in capas.items():

    print("\n" + "="*70)
    print(nombre.upper())
    print("="*70)

    print("\nDIMENSIONES")
    print("-"*70)
    print(f"Filas    : {len(df)}")
    print(f"Columnas : {len(df.columns)}")

    print("\nVALORES NULOS")
    print("-"*70)
    print(df.isnull().sum())

    print("\nREGISTROS DUPLICADOS")
    print("-"*70)
    print(df.duplicated().sum())

    print("\nTIPOS DE DATOS")
    print("-"*70)
    print(df.dtypes)

    print("\nMEMORIA")
    print("-"*70)
    print(df.memory_usage(deep=True))

print("\n")
print("="*70)
print("VALIDACIÓN FINALIZADA")
print("="*70)

M2 - VALIDACIÓN ESTRUCTURAL

CLIMÁTICA

DIMENSIONES
----------------------------------------------------------------------
Filas    : 528
Columnas : 20

VALORES NULOS
----------------------------------------------------------------------
ID_Registro          0
ID_Capa              0
Fecha                0
Precipitacion_mm     0
Temp_Max_C           0
Temp_Min_C           0
Temp_Media_C         0
Humedad_Relativa     0
Velocidad_Viento     0
Radiacion_Solar      0
Nodo                 0
Latitud              0
Longitud             0
Fecha_dt             0
Fecha_ETL            0
Hora_ETL             0
Version_Framework    0
Estado_Registro      0
Responsable          0
Hash                 0
dtype: int64

REGISTROS DUPLICADOS
----------------------------------------------------------------------
0

TIPOS DE DATOS
----------------------------------------------------------------------
ID_Registro                  object
ID_Capa                      object
Fecha                datetime64[ns]

## **M3 Homologación de Llaves**

In [6]:
# ============================================================
# VALIDACIÓN DE LLAVES DE INTEGRACIÓN
# ============================================================

print("\n")
print("="*70)
print("LLAVES DE INTEGRACIÓN")
print("="*70)

for nombre, df in capas.items():

    print(f"\n{nombre}")

    columnas = ["Nodo", "Fecha"]

    faltantes = [c for c in columnas if c not in df.columns]

    if len(faltantes)==0:
        print("✓ Nodo y Fecha encontrados")
    else:
        print("✗ Faltan:", faltantes)



LLAVES DE INTEGRACIÓN

Climática
✓ Nodo y Fecha encontrados

Hidrológica
✗ Faltan: ['Nodo', 'Fecha']

Calidad del Agua
✗ Faltan: ['Nodo', 'Fecha']

ONI
✗ Faltan: ['Nodo']

Hidráulica
✗ Faltan: ['Nodo']

Percepción
✓ Nodo y Fecha encontrados

Gobernanza
✓ Nodo y Fecha encontrados


### **Homologación de Llaves de Integración**

In [7]:
# ============================================================
# HIDROLÓGICA
# ============================================================

hidrologica["Nodo"] = (
    hidrologica["municipio"]
    .astype(str)
    .str.upper()
    .str.strip()
)

hidrologica["Fecha"] = pd.to_datetime(
    hidrologica["fechaobservacion"]
)

In [8]:
# ============================================================
# CALIDAD DEL AGUA
# ============================================================

calidad["Nodo"] = (
    calidad["municipio"]
    .astype(str)
    .str.upper()
    .str.strip()
)

calidad["Fecha"] = pd.to_datetime(
    calidad["fecha"]
)

In [9]:
# ============================================================
# ONI
# ============================================================

oni["Nodo"] = "GLOBAL"

In [10]:
print(hidraulica.columns)

display(hidraulica.head())

Index(['ID_Registro', 'ID_Capa', 'CodigoEmbalse', 'VolumenUtilDiarioMasa',
       'Fecha', 'codigoestacion', 'Fecha_ETL', 'Hora_ETL', 'Version_Framework',
       'Estado_Registro', 'Responsable', 'Hash'],
      dtype='object')


,ID_Registro,ID_Capa,CodigoEmbalse,VolumenUtilDiarioMasa,Fecha,codigoestacion,Fecha_ETL,Hora_ETL,Version_Framework,Estado_Registro,Responsable,Hash
0,HDR-0000001,HDR,AGREGADO_BOGOTA,3.753109e+08,2019-01-31,AGREGADO_BOGOTA,2026-07-14,21:04:45,1.0,VALIDADO,Juan Carlos Riatiga,9f85d57b16edfef2f525bf3aee6b50cc
1,HDR-0000002,HDR,AGREGADO_BOGOTA,3.492289e+08,2019-02-28,AGREGADO_BOGOTA,2026-07-14,21:04:45,1.0,VALIDADO,Juan Carlos Riatiga,23019920cf382148335ab946a342e49b
2,HDR-0000003,HDR,AGREGADO_BOGOTA,3.222146e+08,2019-03-31,AGREGADO_BOGOTA,2026-07-14,21:04:45,1.0,VALIDADO,Juan Carlos Riatiga,5d387075039c58cfae4405eadd78f157
3,HDR-0000004,HDR,AGREGADO_BOGOTA,3.082495e+08,2019-04-30,AGREGADO_BOGOTA,2026-07-14,21:04:45,1.0,VALIDADO,Juan Carlos Riatiga,18e0aee74fdd593e1dd88418c67e88aa
4,HDR-0000005,HDR,AGREGADO_BOGOTA,3.076062e+08,2019-05-31,AGREGADO_BOGOTA,2026-07-14,21:04:45,1.0,VALIDADO,Juan Carlos Riatiga,307d3978e032479fdfe9b14959d7ffde


In [11]:
# ============================================================
# HIDRÁULICA
# Homologación de Nodo
# ============================================================

nodos = [
    "CHIA",
    "SOPO",
    "TOCANCIPA",
    "VILLAPINZON"
]

hidraulica = (
    hidraulica.assign(key=1)
    .merge(
        pd.DataFrame({"Nodo": nodos, "key":1}),
        on="key"
    )
    .drop("key", axis=1)
)

print(hidraulica.shape)

display(hidraulica.head())

(292, 13)


,ID_Registro,ID_Capa,CodigoEmbalse,VolumenUtilDiarioMasa,Fecha,codigoestacion,Fecha_ETL,Hora_ETL,Version_Framework,Estado_Registro,Responsable,Hash,Nodo
0,HDR-0000001,HDR,AGREGADO_BOGOTA,3.753109e+08,2019-01-31,AGREGADO_BOGOTA,2026-07-14,21:04:45,1.0,VALIDADO,Juan Carlos Riatiga,9f85d57b16edfef2f525bf3aee6b50cc,CHIA
1,HDR-0000001,HDR,AGREGADO_BOGOTA,3.753109e+08,2019-01-31,AGREGADO_BOGOTA,2026-07-14,21:04:45,1.0,VALIDADO,Juan Carlos Riatiga,9f85d57b16edfef2f525bf3aee6b50cc,SOPO
2,HDR-0000001,HDR,AGREGADO_BOGOTA,3.753109e+08,2019-01-31,AGREGADO_BOGOTA,2026-07-14,21:04:45,1.0,VALIDADO,Juan Carlos Riatiga,9f85d57b16edfef2f525bf3aee6b50cc,TOCANCIPA
3,HDR-0000001,HDR,AGREGADO_BOGOTA,3.753109e+08,2019-01-31,AGREGADO_BOGOTA,2026-07-14,21:04:45,1.0,VALIDADO,Juan Carlos Riatiga,9f85d57b16edfef2f525bf3aee6b50cc,VILLAPINZON
4,HDR-0000002,HDR,AGREGADO_BOGOTA,3.492289e+08,2019-02-28,AGREGADO_BOGOTA,2026-07-14,21:04:45,1.0,VALIDADO,Juan Carlos Riatiga,23019920cf382148335ab946a342e49b,CHIA


In [12]:
capas = {
    "Climática": climatica,
    "Hidrológica": hidrologica,
    "Calidad": calidad,
    "ONI": oni,
    "Hidráulica": hidraulica,
    "Percepción": percepcion,
    "Gobernanza": gobernanza
}

print("="*70)
print("VERIFICACIÓN FINAL DE LLAVES")
print("="*70)

for nombre, capa in capas.items():

    faltan = []

    if "Nodo" not in capa.columns:
        faltan.append("Nodo")

    if "Fecha" not in capa.columns:
        faltan.append("Fecha")

    print("\n", nombre)

    if len(faltan)==0:
        print("✓ Llaves homologadas")

    else:
        print("Faltan:", faltan)

VERIFICACIÓN FINAL DE LLAVES

 Climática
✓ Llaves homologadas

 Hidrológica
✓ Llaves homologadas

 Calidad
✓ Llaves homologadas

 ONI
✓ Llaves homologadas

 Hidráulica
✓ Llaves homologadas

 Percepción
✓ Llaves homologadas

 Gobernanza
✓ Llaves homologadas


## **M4 Integración Incremental**

### **Construcción de la Base Climática**

In [13]:
# ============================================================
# PASO 1
# CONSTRUCCIÓN DE LA BASE CLIMÁTICA
# ============================================================

print("="*70)
print("PASO 1 - BASE CLIMÁTICA")
print("="*70)

# ============================================================
# Seleccionar únicamente las variables necesarias
# ============================================================

dataset_maestro = climatica.copy()

# ============================================================
# Ordenar registros
# ============================================================

dataset_maestro = (
    dataset_maestro
    .sort_values(["Nodo","Fecha"])
    .reset_index(drop=True)
)

print("\nRegistros:",len(dataset_maestro))
print("Columnas :",len(dataset_maestro.columns))

display(dataset_maestro.head())

PASO 1 - BASE CLIMÁTICA

Registros: 528
Columnas : 20


,ID_Registro,ID_Capa,Fecha,Precipitacion_mm,Temp_Max_C,Temp_Min_C,Temp_Media_C,Humedad_Relativa,Velocidad_Viento,Radiacion_Solar,Nodo,Latitud,Longitud,Fecha_dt,Fecha_ETL,Hora_ETL,Version_Framework,Estado_Registro,Responsable,Hash
0,CLI-0000001,CLI,2015-01-01,2.70,25.30,8.45,18.26,77.88,1.37,17.78,Bogota_Sabana,4.6,-74.15,2015-01-01,2026-07-14,00:16:59,1.0,VALIDADO,Juan Carlos Riatiga,f6ecb4d6b1c181f416196415d8d834d1
1,CLI-0000002,CLI,2015-02-01,2.22,26.14,13.72,19.02,78.83,1.14,17.16,Bogota_Sabana,4.6,-74.15,2015-02-01,2026-07-14,00:16:59,1.0,VALIDADO,Juan Carlos Riatiga,776b0a6e6eb8f63687d1ec358c07d3f2
2,CLI-0000003,CLI,2015-03-01,5.25,27.56,13.52,19.15,80.28,1.09,16.63,Bogota_Sabana,4.6,-74.15,2015-03-01,2026-07-14,00:16:59,1.0,VALIDADO,Juan Carlos Riatiga,c764c4960bf0feca584b82d5157280d2
3,CLI-0000004,CLI,2015-04-01,6.16,25.50,12.81,19.07,80.32,1.07,16.56,Bogota_Sabana,4.6,-74.15,2015-04-01,2026-07-14,00:16:59,1.0,VALIDADO,Juan Carlos Riatiga,c6e8fb40f566fef4d0a462e99fa16c3b
4,CLI-0000005,CLI,2015-05-01,3.27,25.52,12.24,18.99,79.57,1.14,16.00,Bogota_Sabana,4.6,-74.15,2015-05-01,2026-07-14,00:16:59,1.0,VALIDADO,Juan Carlos Riatiga,609e9a31c79c736c2a315774f30f8ccd


In [14]:
dataset_maestro = dataset_maestro[[
    "Nodo",
    "Fecha",
    "Precipitacion_mm",
    "Temp_Max_C",
    "Temp_Min_C",
    "Temp_Media_C",
    "Humedad_Relativa",
    "Velocidad_Viento",
    "Radiacion_Solar"
]]

In [15]:
print(dataset_maestro.shape)

display(dataset_maestro.head())

(528, 9)


,Nodo,Fecha,Precipitacion_mm,Temp_Max_C,Temp_Min_C,Temp_Media_C,Humedad_Relativa,Velocidad_Viento,Radiacion_Solar
0,Bogota_Sabana,2015-01-01,2.70,25.30,8.45,18.26,77.88,1.37,17.78
1,Bogota_Sabana,2015-02-01,2.22,26.14,13.72,19.02,78.83,1.14,17.16
2,Bogota_Sabana,2015-03-01,5.25,27.56,13.52,19.15,80.28,1.09,16.63
3,Bogota_Sabana,2015-04-01,6.16,25.50,12.81,19.07,80.32,1.07,16.56
4,Bogota_Sabana,2015-05-01,3.27,25.52,12.24,18.99,79.57,1.14,16.00


In [16]:
# ============================================================
# VALIDACIÓN PASO 1
# ============================================================

print("="*70)
print("VALIDACIÓN BASE CLIMÁTICA")
print("="*70)

print("\nRegistros :", len(dataset_maestro))
print("Columnas  :", len(dataset_maestro.columns))

print("\nVariables")
print(dataset_maestro.columns.tolist())

print("\nValores nulos")
print(dataset_maestro.isnull().sum())

print("\nDuplicados")
print(dataset_maestro.duplicated(subset=["Nodo","Fecha"]).sum())

print("\nCobertura temporal")
print(dataset_maestro["Fecha"].min())
print(dataset_maestro["Fecha"].max())

print("\nNodos")
print(dataset_maestro["Nodo"].unique())

VALIDACIÓN BASE CLIMÁTICA

Registros : 528
Columnas  : 9

Variables
['Nodo', 'Fecha', 'Precipitacion_mm', 'Temp_Max_C', 'Temp_Min_C', 'Temp_Media_C', 'Humedad_Relativa', 'Velocidad_Viento', 'Radiacion_Solar']

Valores nulos
Nodo                0
Fecha               0
Precipitacion_mm    0
Temp_Max_C          0
Temp_Min_C          0
Temp_Media_C        0
Humedad_Relativa    0
Velocidad_Viento    0
Radiacion_Solar     0
dtype: int64

Duplicados
0

Cobertura temporal
2015-01-01 00:00:00
2025-12-01 00:00:00

Nodos
['Bogota_Sabana' 'Sopo_Sur' 'Tocancipa_Media' 'Villapinzon_Alta']


In [17]:
dataset_maestro["Anio"] = dataset_maestro["Fecha"].dt.year
dataset_maestro["Mes"] = dataset_maestro["Fecha"].dt.month

In [18]:
oni["Anio"] = oni["Fecha"].dt.year
oni["Mes"] = oni["Fecha"].dt.month

In [19]:
oni_merge = oni[[
    "Anio",
    "Mes",
    "ONI",
    "Estado_ENSO"
]].copy()

**Análisis Técnico**

En este primer paso no se realiza ninguna integración entre capas. Se establece la Capa Climática como estructura base del Dataset Maestro debido a que posee la mayor continuidad temporal y constituye el eje común sobre el cual se integrarán progresivamente las variables hidrológicas, hidráulicas, climáticas, de percepción, gobernanza y calidad del agua. Durante esta etapa también se conservan únicamente las variables analíticas necesarias, excluyendo los metadatos propios de la capa original, los cuales serán reemplazados posteriormente por el esquema de gobierno del Dataset Maestro.

### **Integración de la Capa ONI**

In [20]:
# ============================================================
# PASO 2
# INTEGRACIÓN DE LA CAPA ONI
# ============================================================

print("="*70)
print("PASO 2 - INTEGRACIÓN CAPA ONI")
print("="*70)

dataset_maestro = dataset_maestro.merge(

    oni_merge,

    on=["Anio", "Mes"],

    how="left"

)

print("Integración de la capa ONI finalizada.")
print("Dimensiones:", dataset_maestro.shape)

display(dataset_maestro.head())

PASO 2 - INTEGRACIÓN CAPA ONI
Integración de la capa ONI finalizada.
Dimensiones: (528, 13)


,Nodo,Fecha,Precipitacion_mm,Temp_Max_C,Temp_Min_C,Temp_Media_C,Humedad_Relativa,Velocidad_Viento,Radiacion_Solar,Anio,Mes,ONI,Estado_ENSO
0,Bogota_Sabana,2015-01-01,2.70,25.30,8.45,18.26,77.88,1.37,17.78,2015,1,0.68,Niño
1,Bogota_Sabana,2015-02-01,2.22,26.14,13.72,19.02,78.83,1.14,17.16,2015,2,0.57,Niño
2,Bogota_Sabana,2015-03-01,5.25,27.56,13.52,19.15,80.28,1.09,16.63,2015,3,0.57,Niño
3,Bogota_Sabana,2015-04-01,6.16,25.50,12.81,19.07,80.32,1.07,16.56,2015,4,0.82,Niño
4,Bogota_Sabana,2015-05-01,3.27,25.52,12.24,18.99,79.57,1.14,16.00,2015,5,1.03,Niño


In [21]:
dataset_maestro.columns

Index(['Nodo', 'Fecha', 'Precipitacion_mm', 'Temp_Max_C', 'Temp_Min_C',
       'Temp_Media_C', 'Humedad_Relativa', 'Velocidad_Viento',
       'Radiacion_Solar', 'Anio', 'Mes', 'ONI', 'Estado_ENSO'],
      dtype='object')

In [22]:
dataset_maestro.head()

,Nodo,Fecha,Precipitacion_mm,Temp_Max_C,Temp_Min_C,Temp_Media_C,Humedad_Relativa,Velocidad_Viento,Radiacion_Solar,Anio,Mes,ONI,Estado_ENSO
0,Bogota_Sabana,2015-01-01,2.70,25.30,8.45,18.26,77.88,1.37,17.78,2015,1,0.68,Niño
1,Bogota_Sabana,2015-02-01,2.22,26.14,13.72,19.02,78.83,1.14,17.16,2015,2,0.57,Niño
2,Bogota_Sabana,2015-03-01,5.25,27.56,13.52,19.15,80.28,1.09,16.63,2015,3,0.57,Niño
3,Bogota_Sabana,2015-04-01,6.16,25.50,12.81,19.07,80.32,1.07,16.56,2015,4,0.82,Niño
4,Bogota_Sabana,2015-05-01,3.27,25.52,12.24,18.99,79.57,1.14,16.00,2015,5,1.03,Niño


In [23]:
# ============================================================
# VALIDACIÓN CAPA ONI
# ============================================================

print("="*70)
print("VALIDACIÓN CAPA ONI")
print("="*70)

print("\nRegistros :", len(dataset_maestro))
print("Columnas  :", len(dataset_maestro.columns))

print("\nValores nulos")
print(dataset_maestro[["ONI","Estado_ENSO"]].isnull().sum())

print("\nEstados ENSO")
print(dataset_maestro["Estado_ENSO"].value_counts())

display(dataset_maestro.head())

VALIDACIÓN CAPA ONI

Registros : 528
Columnas  : 13

Valores nulos
ONI            0
Estado_ENSO    0
dtype: int64

Estados ENSO
Estado_ENSO
Neutral    196
Niño       176
Niña       156
Name: count, dtype: int64


,Nodo,Fecha,Precipitacion_mm,Temp_Max_C,Temp_Min_C,Temp_Media_C,Humedad_Relativa,Velocidad_Viento,Radiacion_Solar,Anio,Mes,ONI,Estado_ENSO
0,Bogota_Sabana,2015-01-01,2.70,25.30,8.45,18.26,77.88,1.37,17.78,2015,1,0.68,Niño
1,Bogota_Sabana,2015-02-01,2.22,26.14,13.72,19.02,78.83,1.14,17.16,2015,2,0.57,Niño
2,Bogota_Sabana,2015-03-01,5.25,27.56,13.52,19.15,80.28,1.09,16.63,2015,3,0.57,Niño
3,Bogota_Sabana,2015-04-01,6.16,25.50,12.81,19.07,80.32,1.07,16.56,2015,4,0.82,Niño
4,Bogota_Sabana,2015-05-01,3.27,25.52,12.24,18.99,79.57,1.14,16.00,2015,5,1.03,Niño


**Análisis Técnico**

**1. Objetivo técnico**

El objetivo de esta etapa fue incorporar al Dataset Maestro la información correspondiente al **Oceanic Niño Index (ONI)** y la clasificación del estado del fenómeno **El Niño–Oscilación del Sur (ENSO)**, con el propósito de incluir la influencia de la variabilidad climática de gran escala dentro del modelo integrado.

La incorporación de estas variables permite relacionar las condiciones oceánicas globales con las variables climáticas locales registradas en cada uno de los nodos de estudio, proporcionando un contexto climático fundamental para el análisis de la disponibilidad hídrica y el comportamiento ambiental de la región.


**2. Proceso de integración**

Durante el proceso de integración se identificó un desfase temporal en el registro de las fuentes originales:
* La **capa climática** registraba las observaciones utilizando el **primer día de cada mes**.
* La **capa ONI** almacenaba la información correspondiente al **último día de cada mes**.

Esta diferencia impedía una integración directa utilizando la variable `Fecha` como llave principal. Para solucionar esta incompatibilidad se realizó una homologación temporal mediante la construcción y acoplamiento de las variables temporales:

$$\text{Llaves de unión: } \{\text{Año, Mes}\}$$

Este procedimiento permitió asociar correctamente cada registro climático con el valor mensual del índice ONI y su correspondiente clasificación ENSO, independientemente del día específico utilizado por cada fuente de datos.

**3. Validación de la integración**

Una vez realizada la integración se verificaron diversos criterios de calidad para garantizar la consistencia del Dataset Maestro.

* **Conservación de registros**

  El proceso mantuvo intacta la estructura del Dataset Maestro, logrando una relación de integración **uno a uno**:

  | Indicador | Resultado |
  | :--- | :--- |
  | **Registros antes** | 528 |
  | **Registros después** | 528 |
  | **Duplicados generados** | 0 |

* **Completitud de las variables integradas**

  Se evaluó la presencia de nulos en los nuevos atributos incorporados (`ONI` y `Estado_ENSO`):

  | Variable | Valores nulos |
  | :--- | :--- |
  | **`ONI`** | 0 |
  | **`Estado_ENSO`** | 0 |

  La ausencia absoluta de valores faltantes demuestra que la cobertura temporal del índice ONI coincide completamente con el periodo analizado en la capa climática.

* **Distribución de los estados ENSO**

  La distribución de los registros según la clasificación climática consolidada se detalla a continuación:

  | Estado ENSO | Registros |
  | :--- | :--- |
  | **Neutral** | 196 |
  | **Niño** | 176 |
  | **Niña** | 156 |

  Esta distribución evidencia que el Dataset Maestro incorpora observaciones balanceadas de las tres fases del fenómeno ENSO, permitiendo un análisis robusto de la influencia de cada estado sobre las variables hidroclimáticas locales.

* **Validación temporal (Muestra de registros)**

  La revisión de los primeros registros permitió confirmar la correcta correspondencia entre las observaciones climáticas y el índice oceánico mensual:

  | Fecha Climática | ONI | Estado ENSO |
  | :--- | :--- | :--- |
  | Enero 2015 | 0.68 | **Niño** |
  | Febrero 2015 | 0.57 | **Niño** |
  | Marzo 2015 | 0.57 | **Niño** |
  | Abril 2015 | 0.82 | **Niño** |
  | Mayo 2015 | 1.03 | **Niño** |



**4. Resultado obtenido**

Como resultado de esta etapa, el Dataset Maestro amplió su estructura incorporando dos nuevas dimensiones científicas:

| Dominio | Variables integradas |
| :--- | :--- |
| **Climático** | Precipitación, temperatura máxima, temperatura mínima, temperatura media, humedad relativa, velocidad del viento y radiación solar. |
| **Oceánico** | Índice ONI y clasificación ENSO (`Estado_ENSO`). |

La integración del índice ONI permite contextualizar las condiciones meteorológicas locales dentro del comportamiento climático del océano Pacífico ecuatorial, facilitando el análisis conjunto entre los fenómenos oceánicos y las variables atmosféricas registradas en la región.


**5. Importancia dentro del Framework**

La integración de la capa ONI constituye el primer paso hacia la construcción de un Dataset Maestro Multicapa, al incorporar una fuente de información externa de alcance global dentro del modelo de datos del Framework.

Desde el punto de vista metodológico, esta etapa demuestra la capacidad del Framework para integrar fuentes heterogéneas con diferentes representaciones temporales mediante procesos de homologación de llaves. La transformación de la fecha en componentes de `Año` y `Mes` permitió establecer una correspondencia consistente entre ambas capas sin modificar la información original de las fuentes.

Asimismo, la incorporación del índice ONI aporta una dimensión explicativa fundamental para los análisis posteriores, ya que permite evaluar la influencia de los eventos El Niño, La Niña y Neutral sobre el comportamiento climático, hidrológico e hidráulico de la región de estudio. Esta información será esencial durante las fases de ingeniería de características (*Feature Engineering*) y entrenamiento de los modelos de inteligencia artificial, al incorporar un indicador reconocido internacionalmente como variable predictora del comportamiento hidroclimático.

### **Integración de la Capa Hidráulica**

In [24]:
# ============================================================
# PASO 3
# INTEGRACIÓN DE LA CAPA HIDRÁULICA
# ============================================================

print("="*70)
print("PREPARACIÓN CAPA HIDRÁULICA")
print("="*70)

# Año y mes

hidraulica["Anio"] = hidraulica["Fecha"].dt.year
hidraulica["Mes"]  = hidraulica["Fecha"].dt.month

# Homologación de nodos

hidraulica["Nodo"] = hidraulica["Nodo"].replace({

    "CHIA":"Bogota_Sabana",

    "SOPO":"Sopo_Sur",

    "TOCANCIPA":"Tocancipa_Media",

    "VILLAPINZON":"Villapinzon_Alta"

})

# Variables necesarias

hidraulica_merge = hidraulica[[

    "Nodo",

    "Anio",

    "Mes",

    "VolumenUtilDiarioMasa"

]].copy()

print("\nDimensiones")

print(hidraulica_merge.shape)

display(hidraulica_merge.head())

PREPARACIÓN CAPA HIDRÁULICA

Dimensiones
(292, 4)


,Nodo,Anio,Mes,VolumenUtilDiarioMasa
0,Bogota_Sabana,2019,1,3.753109e+08
1,Sopo_Sur,2019,1,3.753109e+08
2,Tocancipa_Media,2019,1,3.753109e+08
3,Villapinzon_Alta,2019,1,3.753109e+08
4,Bogota_Sabana,2019,2,3.492289e+08


In [25]:
print(hidraulica_merge["Nodo"].unique())

print(hidraulica_merge["Anio"].min(), hidraulica_merge["Anio"].max())

print(hidraulica_merge["Mes"].unique())

display(hidraulica_merge.head())

['Bogota_Sabana' 'Sopo_Sur' 'Tocancipa_Media' 'Villapinzon_Alta']
2019 2025
[ 1  2  3  4  5  6  7  8  9 10 11 12]


,Nodo,Anio,Mes,VolumenUtilDiarioMasa
0,Bogota_Sabana,2019,1,3.753109e+08
1,Sopo_Sur,2019,1,3.753109e+08
2,Tocancipa_Media,2019,1,3.753109e+08
3,Villapinzon_Alta,2019,1,3.753109e+08
4,Bogota_Sabana,2019,2,3.492289e+08


In [26]:

print("="*70)
print("PASO 3 - INTEGRACIÓN CAPA HIDRÁULICA")
print("="*70)

dataset_maestro = dataset_maestro.merge(

    hidraulica_merge,

    on=["Nodo","Anio","Mes"],

    how="left"

)

print("\nIntegración finalizada.")

print("\nDimensiones:")

print(dataset_maestro.shape)

display(dataset_maestro.head())

PASO 3 - INTEGRACIÓN CAPA HIDRÁULICA

Integración finalizada.

Dimensiones:
(528, 14)


,Nodo,Fecha,Precipitacion_mm,Temp_Max_C,Temp_Min_C,Temp_Media_C,Humedad_Relativa,Velocidad_Viento,Radiacion_Solar,Anio,Mes,ONI,Estado_ENSO,VolumenUtilDiarioMasa
0,Bogota_Sabana,2015-01-01,2.70,25.30,8.45,18.26,77.88,1.37,17.78,2015,1,0.68,Niño,NaN
1,Bogota_Sabana,2015-02-01,2.22,26.14,13.72,19.02,78.83,1.14,17.16,2015,2,0.57,Niño,NaN
2,Bogota_Sabana,2015-03-01,5.25,27.56,13.52,19.15,80.28,1.09,16.63,2015,3,0.57,Niño,NaN
3,Bogota_Sabana,2015-04-01,6.16,25.50,12.81,19.07,80.32,1.07,16.56,2015,4,0.82,Niño,NaN
4,Bogota_Sabana,2015-05-01,3.27,25.52,12.24,18.99,79.57,1.14,16.00,2015,5,1.03,Niño,NaN


In [27]:
print("="*70)
print("VALIDACIÓN CAPA HIDRÁULICA")
print("="*70)

print("\nRegistros :", len(dataset_maestro))
print("Columnas  :", len(dataset_maestro.columns))

print("\nValores nulos")

print(
    dataset_maestro[
        ["VolumenUtilDiarioMasa"]
    ].isnull().sum()
)

print("\nCobertura")

print(
    dataset_maestro["VolumenUtilDiarioMasa"].describe()
)

display(dataset_maestro.head())

VALIDACIÓN CAPA HIDRÁULICA

Registros : 528
Columnas  : 14

Valores nulos
VolumenUtilDiarioMasa    236
dtype: int64

Cobertura
count    2.920000e+02
mean     4.396593e+08
std      1.000797e+08
min      2.901419e+08
25%      3.364336e+08
50%      4.548644e+08
75%      5.329571e+08
max      6.195856e+08
Name: VolumenUtilDiarioMasa, dtype: float64


,Nodo,Fecha,Precipitacion_mm,Temp_Max_C,Temp_Min_C,Temp_Media_C,Humedad_Relativa,Velocidad_Viento,Radiacion_Solar,Anio,Mes,ONI,Estado_ENSO,VolumenUtilDiarioMasa
0,Bogota_Sabana,2015-01-01,2.70,25.30,8.45,18.26,77.88,1.37,17.78,2015,1,0.68,Niño,NaN
1,Bogota_Sabana,2015-02-01,2.22,26.14,13.72,19.02,78.83,1.14,17.16,2015,2,0.57,Niño,NaN
2,Bogota_Sabana,2015-03-01,5.25,27.56,13.52,19.15,80.28,1.09,16.63,2015,3,0.57,Niño,NaN
3,Bogota_Sabana,2015-04-01,6.16,25.50,12.81,19.07,80.32,1.07,16.56,2015,4,0.82,Niño,NaN
4,Bogota_Sabana,2015-05-01,3.27,25.52,12.24,18.99,79.57,1.14,16.00,2015,5,1.03,Niño,NaN


In [28]:
dataset_maestro[
    dataset_maestro["Anio"] >= 2019
][
    ["Nodo","Fecha","VolumenUtilDiarioMasa"]
].head(20)

,Nodo,Fecha,VolumenUtilDiarioMasa
48,Bogota_Sabana,2019-01-01,3.753109e+08
49,Bogota_Sabana,2019-02-01,3.492289e+08
50,Bogota_Sabana,2019-03-01,3.222146e+08
51,Bogota_Sabana,2019-04-01,3.082495e+08
52,Bogota_Sabana,2019-05-01,3.076062e+08
53,Bogota_Sabana,2019-06-01,3.217828e+08
54,Bogota_Sabana,2019-07-01,3.662438e+08
55,Bogota_Sabana,2019-08-01,3.900549e+08
56,Bogota_Sabana,2019-09-01,3.992587e+08
57,Bogota_Sabana,2019-10-01,3.925679e+08


**Análisis Técnico**

**1. Objetivo técnico**

El propósito de esta etapa fue incorporar al Dataset Maestro la información correspondiente al comportamiento hidráulico de los embalses que abastecen la región de estudio, permitiendo relacionar las variables climáticas y oceánicas previamente integradas con la disponibilidad hídrica almacenada.

Para ello, se utilizó la variable **`VolumenUtilDiarioMasa`**, la cual representa el volumen útil disponible en los embalses durante cada periodo de observación.

**2. Proceso de integración**

La integración se realizó mediante un proceso de unión (*merge*) utilizando tres llaves comunes previamente homologadas dentro del Framework:

* **`Nodo`** (Espacial)
* **`Año`** (Temporal)
* **`Mes`** (Temporal)

El uso de estas llaves permitió resolver las diferencias existentes entre las estructuras originales de ambas capas, garantizando una correspondencia temporal y espacial consistente.

* **Homologación de Nombres**

  Debido a que la capa hidráulica utilizaba inicialmente una nomenclatura distinta para los municipios, fue necesario realizar previamente un proceso de homologación de nombres hacia la estructura estándar utilizada por el Framework:

  | Capa Hidráulica | Dataset Maestro (Estándar) |
  | :--- | :--- |
  | `CHIA` | **Bogota_Sabana** |
  | `SOPO` | **Sopo_Sur** |
  | `TOCANCIPA` | **Tocancipa_Media** |
  | `VILLAPINZON` | **Villapinzon_Alta** |

  Una vez realizada esta homologación, la integración pudo ejecutarse utilizando una única llave espacial estandarizada.

**3. Validación de la integración**
Después del proceso de integración se verificaron múltiples aspectos de calidad del dato:

* **Conservación de registros**
  El Dataset Maestro conservó los **528 registros originales**, lo que demuestra que la operación de unión no produjo pérdidas ni duplicaciones de información.

  | Indicador | Resultado |
  | :--- | :--- |
  | **Registros antes** | 528 |
  | **Registros después** | 528 |
  | **Duplicados generados** | 0 |

  Este comportamiento confirma una relación de integración **uno a uno** entre ambas capas.

* **Cobertura temporal**

  Durante la validación se observó que la capa hidráulica únicamente dispone de información comprendida entre los años **2019 y 2025**, mientras que la capa climática inicia en **2015**.

  * Como consecuencia, los registros correspondientes al periodo **2015–2018** permanecen sin información hidráulica.

  * Esta situación era esperada y responde a la disponibilidad histórica de la fuente de datos, no a errores en el proceso ETL.

* **Completitud de la variable integrada**

  La variable `VolumenUtilDiarioMasa` presentó:

    * **292** registros con información.
    * **236** registros sin información (`NaN`).

  Los valores faltantes corresponden principalmente a periodos anteriores a 2019 y a algunos meses específicos para los cuales la fuente hidráulica no dispone de registros. La conservación explícita de estos valores faltantes evita introducir información artificial mediante procesos de imputación, preservando la fidelidad de los datos originales.

* **Validación estadística**

  La variable integrada presentó estadísticas descriptivas coherentes:

  * **Valor mínimo:** cercano a $2.90 \times 10^8 \text{ m}^3$
  * **Valor máximo:** superior a $6.19 \times 10^8 \text{ m}^3$
  * Distribución continua sin anomalías derivadas del proceso de integración.

  La generación correcta de estas estadísticas confirma que la variable fue incorporada como dato numérico (`float`) y no sufrió alteraciones de formato durante el proceso ETL.

**4. Resultado obtenido**

Como resultado de esta etapa, el Dataset Maestro incorpora simultáneamente información proveniente de tres dominios científicos:

| Dominio | Variables integradas |
| :--- | :--- |
| **Climático** | Precipitación, temperatura máxima, temperatura mínima, temperatura media, humedad relativa, velocidad del viento y radiación solar. |
| **Oceánico** | Índice ONI y clasificación ENSO. |
| **Hidráulico** | Volumen útil diario de los embalses (`VolumenUtilDiarioMasa`). |

Esta integración permite comenzar a representar la relación existente entre las condiciones atmosféricas, la variabilidad climática de gran escala y la disponibilidad de agua almacenada en los sistemas hidráulicos.

**5. Importancia dentro del Framework**

La incorporación de la capa hidráulica representa un avance significativo en la construcción del Dataset Maestro, ya que introduce la dimensión de almacenamiento hídrico al modelo integrado. Mientras las variables climáticas describen las condiciones atmosféricas y la capa ONI caracteriza la influencia de fenómenos oceánicos globales, la información hidráulica refleja la respuesta operativa del sistema de embalses frente a dichas condiciones.

Desde el punto de vista metodológico, esta etapa valida la capacidad del Framework para integrar fuentes heterogéneas con diferentes coberturas espaciales y temporales mediante un esquema de homologación de llaves y un proceso ETL reproducible. Asimismo, establece una base sólida para las siguientes fases de integración, en las cuales se incorporarán variables de percepción ciudadana, gobernanza, hidrología y calidad del agua, conformando un conjunto de datos multidimensional orientado al análisis científico y al desarrollo de modelos de inteligencia artificial aplicados a la gestión sostenible del recurso hídrico.

**6. Observación metodológica:**

Este es uno de los hitos más importantes de la investigación. A partir de este punto, el proyecto deja de trabajar con siete datasets independientes para pasar a construir un **Dataset Maestro Multicapa**, el cual constituye el aporte diferencial del Framework y la base para el desarrollo de la ingeniería de características y el modelado predictivo con IA. Este cambio de enfoque marca la transición desde la simple preparación de datos hacia la consolidación de un activo analítico integrado.

### **Integración de la Capa Percepción**

In [29]:
# ============================================================
# PASO 4
# INTEGRACIÓN DE LA CAPA DE PERCEPCION
# ============================================================

print(percepcion.columns)

display(percepcion.head())

print(percepcion.dtypes)

print(percepcion["Nodo"].unique())

print(
    percepcion["Fecha"].min(),
    percepcion["Fecha"].max()
)

Index(['ID_Registro', 'ID_Capa', 'Nodo', 'municipio', 'a_o', 'Fecha', 'irca',
       'nivel_de_riesgo', 'codigoestacion', 'Fecha_ETL', 'Hora_ETL',
       'Version_Framework', 'Estado_Registro', 'Responsable', 'Hash'],
      dtype='object')


,ID_Registro,ID_Capa,Nodo,municipio,a_o,Fecha,irca,nivel_de_riesgo,codigoestacion,Fecha_ETL,Hora_ETL,Version_Framework,Estado_Registro,Responsable,Hash
0,PER-0000001,PER,"Bogotá, D.C.","Bogotá, D.C.",2007,2007-12-31,0.1,Sin riesgo,"Bogotá, D.C.",2026-07-14,23:25:00,1.0,VALIDADO,Juan Carlos Riatiga,20a78f108cdb4831286fcad92b8f7b26
1,PER-0000002,PER,"Bogotá, D.C.","Bogotá, D.C.",2008,2008-12-31,8.6,Riesgo bajo,"Bogotá, D.C.",2026-07-14,23:25:00,1.0,VALIDADO,Juan Carlos Riatiga,9947425e1089a2e239b1d7b674c29c45
2,PER-0000003,PER,"Bogotá, D.C.","Bogotá, D.C.",2009,2009-12-31,14.3,Riesgo medio,"Bogotá, D.C.",2026-07-14,23:25:00,1.0,VALIDADO,Juan Carlos Riatiga,913d31260b13bc883224a99212c8b25d
3,PER-0000004,PER,"Bogotá, D.C.","Bogotá, D.C.",2010,2010-12-31,10.2,Riesgo bajo,"Bogotá, D.C.",2026-07-14,23:25:00,1.0,VALIDADO,Juan Carlos Riatiga,96a9ea481cf80d47f5315395a9183d6f
4,PER-0000005,PER,"Bogotá, D.C.","Bogotá, D.C.",2011,2011-12-31,8.6,Riesgo bajo,"Bogotá, D.C.",2026-07-14,23:25:00,1.0,VALIDADO,Juan Carlos Riatiga,18ca839da3556aba1b192cbd6f6a0deb


ID_Registro                  object
ID_Capa                      object
Nodo                         object
municipio                    object
a_o                           int64
Fecha                datetime64[ns]
irca                        float64
nivel_de_riesgo              object
codigoestacion               object
Fecha_ETL                    object
Hora_ETL                     object
Version_Framework           float64
Estado_Registro              object
Responsable                  object
Hash                         object
dtype: object
['Bogotá, D.C.' 'Chía' 'Tocancipá' 'Villapinzón']
2007-12-31 00:00:00 2024-12-31 00:00:00


In [30]:
# Homologar nodos

percepcion["Nodo"] = percepcion["Nodo"].replace({

    "Bogotá, D.C.": "Bogota_Sabana",
    "Chía": "Sopo_Sur",
    "Tocancipá": "Tocancipa_Media",
    "Villapinzón": "Villapinzon_Alta"

})

In [31]:
# Crear Año
percepcion["Anio"] = percepcion["Fecha"].dt.year

In [32]:
# ============================================================
# PASO 4.3
# EXPANSIÓN TEMPORAL DE LA CAPA PERCEPCIÓN
# ============================================================

print("="*70)
print("EXPANSIÓN TEMPORAL - CAPA PERCEPCIÓN")
print("="*70)

# ============================================================
# Homologar nombres de Nodo
# ============================================================

percepcion["Nodo"] = percepcion["Nodo"].replace({

    "Bogotá, D.C.": "Bogota_Sabana",
    "Chía": "Sopo_Sur",
    "Tocancipá": "Tocancipa_Media",
    "Villapinzón": "Villapinzon_Alta"

})

# ============================================================
# Crear Año
# ============================================================

percepcion["Anio"] = percepcion["Fecha"].dt.year

# ============================================================
# Expandir a los 12 meses
# ============================================================

percepcion_expandida = (
    percepcion
    .loc[percepcion.index.repeat(12)]
    .reset_index(drop=True)
)

percepcion_expandida["Mes"] = list(range(1,13)) * len(percepcion)

# ============================================================
# Seleccionar variables para integración
# ============================================================

percepcion_merge = percepcion_expandida[[

    "Nodo",
    "Anio",
    "Mes",
    "irca",
    "nivel_de_riesgo"

]].copy()

print("\nProceso finalizado correctamente.")

print("\nDimensiones:", percepcion_merge.shape)

display(percepcion_merge.head(15))

EXPANSIÓN TEMPORAL - CAPA PERCEPCIÓN

Proceso finalizado correctamente.

Dimensiones: (864, 5)


,Nodo,Anio,Mes,irca,nivel_de_riesgo
0,Bogota_Sabana,2007,1,0.1,Sin riesgo
1,Bogota_Sabana,2007,2,0.1,Sin riesgo
2,Bogota_Sabana,2007,3,0.1,Sin riesgo
3,Bogota_Sabana,2007,4,0.1,Sin riesgo
4,Bogota_Sabana,2007,5,0.1,Sin riesgo
5,Bogota_Sabana,2007,6,0.1,Sin riesgo
6,Bogota_Sabana,2007,7,0.1,Sin riesgo
7,Bogota_Sabana,2007,8,0.1,Sin riesgo
8,Bogota_Sabana,2007,9,0.1,Sin riesgo
9,Bogota_Sabana,2007,10,0.1,Sin riesgo


In [33]:
print(percepcion_merge.shape)

print(percepcion_merge["Nodo"].unique())

print(
    percepcion_merge["Anio"].min(),
    percepcion_merge["Anio"].max()
)

print(sorted(percepcion_merge["Mes"].unique()))

display(percepcion_merge.head(15))

(864, 5)
['Bogota_Sabana' 'Sopo_Sur' 'Tocancipa_Media' 'Villapinzon_Alta']
2007 2024
[np.int64(1), np.int64(2), np.int64(3), np.int64(4), np.int64(5), np.int64(6), np.int64(7), np.int64(8), np.int64(9), np.int64(10), np.int64(11), np.int64(12)]


,Nodo,Anio,Mes,irca,nivel_de_riesgo
0,Bogota_Sabana,2007,1,0.1,Sin riesgo
1,Bogota_Sabana,2007,2,0.1,Sin riesgo
2,Bogota_Sabana,2007,3,0.1,Sin riesgo
3,Bogota_Sabana,2007,4,0.1,Sin riesgo
4,Bogota_Sabana,2007,5,0.1,Sin riesgo
5,Bogota_Sabana,2007,6,0.1,Sin riesgo
6,Bogota_Sabana,2007,7,0.1,Sin riesgo
7,Bogota_Sabana,2007,8,0.1,Sin riesgo
8,Bogota_Sabana,2007,9,0.1,Sin riesgo
9,Bogota_Sabana,2007,10,0.1,Sin riesgo


In [34]:

print("="*70)
print("PASO 4 - INTEGRACIÓN CAPA PERCEPCIÓN")
print("="*70)

dataset_maestro = dataset_maestro.merge(

    percepcion_merge,

    on=["Nodo","Anio","Mes"],

    how="left"

)

print("\nIntegración realizada correctamente.")

print("\nDimensiones:", dataset_maestro.shape)

display(dataset_maestro.head())

PASO 4 - INTEGRACIÓN CAPA PERCEPCIÓN

Integración realizada correctamente.

Dimensiones: (528, 16)


,Nodo,Fecha,Precipitacion_mm,Temp_Max_C,Temp_Min_C,Temp_Media_C,Humedad_Relativa,Velocidad_Viento,Radiacion_Solar,Anio,Mes,ONI,Estado_ENSO,VolumenUtilDiarioMasa,irca,nivel_de_riesgo
0,Bogota_Sabana,2015-01-01,2.70,25.30,8.45,18.26,77.88,1.37,17.78,2015,1,0.68,Niño,NaN,7.4,Riesgo bajo
1,Bogota_Sabana,2015-02-01,2.22,26.14,13.72,19.02,78.83,1.14,17.16,2015,2,0.57,Niño,NaN,7.4,Riesgo bajo
2,Bogota_Sabana,2015-03-01,5.25,27.56,13.52,19.15,80.28,1.09,16.63,2015,3,0.57,Niño,NaN,7.4,Riesgo bajo
3,Bogota_Sabana,2015-04-01,6.16,25.50,12.81,19.07,80.32,1.07,16.56,2015,4,0.82,Niño,NaN,7.4,Riesgo bajo
4,Bogota_Sabana,2015-05-01,3.27,25.52,12.24,18.99,79.57,1.14,16.00,2015,5,1.03,Niño,NaN,7.4,Riesgo bajo


In [35]:
print("="*70)
print("VALIDACIÓN CAPA PERCEPCIÓN")
print("="*70)

print("\nRegistros :", len(dataset_maestro))
print("Columnas  :", len(dataset_maestro.columns))

print("\nValores nulos")

print(
    dataset_maestro[
        ["irca","nivel_de_riesgo"]
    ].isnull().sum()
)

print("\nDistribución nivel de riesgo")

print(
    dataset_maestro["nivel_de_riesgo"]
    .value_counts(dropna=False)
)

display(

dataset_maestro[
    [
        "Nodo",
        "Fecha",
        "irca",
        "nivel_de_riesgo"
    ]
].head(20)

)

VALIDACIÓN CAPA PERCEPCIÓN

Registros : 528
Columnas  : 16

Valores nulos
irca               48
nivel_de_riesgo    48
dtype: int64

Distribución nivel de riesgo
nivel_de_riesgo
Sin riesgo     396
Riesgo bajo     84
NaN             48
Name: count, dtype: int64


,Nodo,Fecha,irca,nivel_de_riesgo
0,Bogota_Sabana,2015-01-01,7.4,Riesgo bajo
1,Bogota_Sabana,2015-02-01,7.4,Riesgo bajo
2,Bogota_Sabana,2015-03-01,7.4,Riesgo bajo
3,Bogota_Sabana,2015-04-01,7.4,Riesgo bajo
4,Bogota_Sabana,2015-05-01,7.4,Riesgo bajo
5,Bogota_Sabana,2015-06-01,7.4,Riesgo bajo
6,Bogota_Sabana,2015-07-01,7.4,Riesgo bajo
7,Bogota_Sabana,2015-08-01,7.4,Riesgo bajo
8,Bogota_Sabana,2015-09-01,7.4,Riesgo bajo
9,Bogota_Sabana,2015-10-01,7.4,Riesgo bajo


**Análisis Técnico**

**1. Objetivo**

Incorporar al Dataset Maestro los indicadores de percepción de la calidad del agua mediante el **Índice de Riesgo de la Calidad del Agua para Consumo Humano (IRCA)**, integrando una dimensión social y sanitaria al conjunto de variables ambientales previamente consolidadas.

**2. Desarrollo técnico**

La capa de Percepción presentaba una resolución temporal anual, mientras que el Dataset Maestro se estructuró con periodicidad mensual. Para garantizar la compatibilidad entre ambas estructuras, se ejecutaron dos subprocesos clave:

* **Expansión Temporal:** Se replicó cada registro anual a los doce meses correspondientes.
* **Homologación Territorial:** Se estandarizaron los nombres de los nodos territoriales para asegurar la consistencia de las llaves de integración.

Posteriormente, la integración se efectuó mediante un **`left join`** utilizando la siguiente llave de unión combinada:

$$\text{Llaves de integración: } \{\text{Nodo, Año, Mes}\}$$

Este procedimiento permitió conservar la totalidad de los registros del Dataset Maestro e incorporar de manera consistente las variables **`IRCA`** y **`nivel de riesgo`**.

**3. Resultados obtenidos**

La integración permitió incorporar exitosamente los indicadores de percepción para el período comprendido entre **2015 y 2024**.

**Validación de Completitud y Consistencia**

* **Periodo 2015–2024:** Completitud total de los datos de percepción integrados.
* **Periodo 2025:** Registros ausentes debido a la inexistencia de información en la fuente original. Esto generó exactamente **48 registros vacíos (NaN)**, calculados como:

$$\text{4 nodos} \times \text{12 meses} = 48 \text{ registros sin información}$$

Este comportamiento es completamente normal y esperado dentro de la lógica del proceso de integración.

**Distribución de las Categorías de Riesgo**

La distribución de las clasificaciones obtenidas conservó la estructura original de la fuente, con un predominio de registros en las categorías:
* **Sin riesgo**
* **Riesgo bajo**

No se evidenciaron inconsistencias de formato, pérdida de filas ni alteraciones de los límites categóricos durante la homologación o el proceso de unión.

**4. Importancia científica**

La incorporación del IRCA añade una **dimensión sanitaria** al Framework, permitiendo relacionar variables climáticas, hidrológicas e hidráulicas con indicadores de calidad del agua para consumo humano.

Esta integración amplía la capacidad analítica del Dataset Maestro y proporciona una base más robusta para el desarrollo de modelos de inteligencia artificial orientados a comprender las complejas interacciones entre:
* Las condiciones ambientales.
* La disponibilidad física del recurso hídrico.
* El riesgo asociado a la calidad del agua potable en los territorios.

### **Integración de la Capa de Gobernanza**

In [36]:
# ============================================================
# PASO 5
# INTEGRACIÓN DE LA CAPA DE GOBERNANZA
# ============================================================

print("="*70)
print("CAPA GOBERNANZA")
print("="*70)

print("\nDimensiones")
print(gobernanza.shape)

print("\nColumnas")
print(gobernanza.columns)

print("\nTipos")
print(gobernanza.dtypes)

print("\nPrimeros registros")
display(gobernanza.head())

print("\nCobertura temporal")
print(
    gobernanza["Fecha"].min(),
    gobernanza["Fecha"].max()
)

print("\nNodos")
print(gobernanza["Nodo"].unique())

CAPA GOBERNANZA

Dimensiones
(20, 22)

Columnas
Index(['ID_Registro', 'ID_Capa', 'Nodo', 'Fecha', 'COD_MUN', 'MUNICIPIO',
       'Anio', 'POBLACION TOTAL', 'DENSIDAD POBLACIONAL',
       'PORCENTAJE POBLACION URBANA', 'PORCENTAJE POBLACION RURAL',
       'PRODUCTO INTERNO BRUTO DEPARTAMENTAL',
       'INDICE DE DESEMPENO INSTITUCIONAL', 'ACCESO A AGUA POTABLE ADECUADO',
       'PORCENTAJE DE LA POBLACION CON ACCESO A METODOS DE SANEAMIENTO ADECUADOS',
       'COBERTURA DE ACUEDUCTO URBANO', 'COBERTURA DE ACUEDUCTO RURAL',
       'COBERTURA DE ALCANTARILLADO URBANO',
       'COBERTURA DE ALCANTARILLADO RURAL', 'CONTINUIDAD DE ACUEDUCTO URBANO',
       'CALIDAD DEL AGUA', 'AGUAS RESIDUALES TRATADAS'],
      dtype='object')

Tipos
ID_Registro                                                                         object
ID_Capa                                                                             object
Nodo                                                                            

,ID_Registro,ID_Capa,Nodo,Fecha,COD_MUN,MUNICIPIO,Anio,POBLACION TOTAL,DENSIDAD POBLACIONAL,PORCENTAJE POBLACION URBANA,...,INDICE DE DESEMPENO INSTITUCIONAL,ACCESO A AGUA POTABLE ADECUADO,PORCENTAJE DE LA POBLACION CON ACCESO A METODOS DE SANEAMIENTO ADECUADOS,COBERTURA DE ACUEDUCTO URBANO,COBERTURA DE ACUEDUCTO RURAL,COBERTURA DE ALCANTARILLADO URBANO,COBERTURA DE ALCANTARILLADO RURAL,CONTINUIDAD DE ACUEDUCTO URBANO,CALIDAD DEL AGUA,AGUAS RESIDUALES TRATADAS
0,GOB-0000001,GOB,CHIA,2020-12-31,25175,CHIA,2020,NaN,NaN,83.11,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,GOB-0000002,GOB,CHIA,2021-12-31,25175,CHIA,2021,148415.0,1952.83,83.72,...,NaN,100.0,99.00,100.0,100.0,84.66,61.07,NaN,NaN,NaN
2,GOB-0000003,GOB,CHIA,2022-12-31,25175,CHIA,2022,153130.0,2014.87,84.17,...,NaN,100.0,99.00,1.0,100.0,98.09,59.83,NaN,NaN,NaN
3,GOB-0000004,GOB,CHIA,2023-12-31,25175,CHIA,2023,158258.0,2082.34,84.58,...,NaN,100.0,98.85,1.0,100.0,99.00,1.00,24.0,25.00,69.0
4,GOB-0000005,GOB,CHIA,2024-12-31,25175,CHIA,2024,163306.0,2148.76,84.97,...,69.6,100.0,98.85,1.0,100.0,99.00,1.00,24.0,36.32,69.0



Cobertura temporal
2020-12-31 00:00:00 2024-12-31 00:00:00

Nodos
['CHIA' 'SOPO' 'TOCANCIPA' 'VILLAPINZON']


In [37]:
# ============================================================
# HOMOLOGACIÓN DE NODOS
# ============================================================

gobernanza["Nodo"] = gobernanza["Nodo"].replace({

    "CHIA":"Bogota_Sabana",
    "SOPO":"Sopo_Sur",
    "TOCANCIPA":"Tocancipa_Media",
    "VILLAPINZON":"Villapinzon_Alta"

})

In [38]:
print(gobernanza["Nodo"].unique())

['Bogota_Sabana' 'Sopo_Sur' 'Tocancipa_Media' 'Villapinzon_Alta']


In [39]:
# ============================================================
# EXPANDIR A 12 MESES
# ============================================================

filas = []

for _, fila in gobernanza.iterrows():

    for mes in range(1,13):

        nueva = fila.copy()

        nueva["Mes"] = mes

        filas.append(nueva)

gobernanza = pd.DataFrame(filas)

In [40]:
gobernanza["Anio"] = gobernanza["Anio"].astype(int)

In [41]:
gobernanza_merge = gobernanza[[

    "Nodo",
    "Anio",
    "Mes",

    "POBLACION TOTAL",
    "DENSIDAD POBLACIONAL",
    "INDICE DE DESEMPENO INSTITUCIONAL",
    "ACCESO A AGUA POTABLE ADECUADO",
    "PORCENTAJE DE LA POBLACION CON ACCESO A METODOS DE SANEAMIENTO ADECUADOS",
    "COBERTURA DE ACUEDUCTO URBANO",
    "COBERTURA DE ACUEDUCTO RURAL",
    "COBERTURA DE ALCANTARILLADO URBANO",
    "COBERTURA DE ALCANTARILLADO RURAL",
    "CONTINUIDAD DE ACUEDUCTO URBANO",
    "CALIDAD DEL AGUA",
    "AGUAS RESIDUALES TRATADAS"

]].copy()

In [42]:
print("="*70)
print("CAPA GOBERNANZA PREPARADA")
print("="*70)

print()

print("Dimensiones")
print(gobernanza_merge.shape)

print()

print("Cobertura temporal")
print(gobernanza_merge["Anio"].min(),
      gobernanza_merge["Anio"].max())

print()

print("Meses")
print(sorted(gobernanza_merge["Mes"].unique()))

print()

print("Nodos")
print(gobernanza_merge["Nodo"].unique())

display(gobernanza_merge.head(10))

CAPA GOBERNANZA PREPARADA

Dimensiones
(240, 15)

Cobertura temporal
2020 2024

Meses
[np.int64(1), np.int64(2), np.int64(3), np.int64(4), np.int64(5), np.int64(6), np.int64(7), np.int64(8), np.int64(9), np.int64(10), np.int64(11), np.int64(12)]

Nodos
['Bogota_Sabana' 'Sopo_Sur' 'Tocancipa_Media' 'Villapinzon_Alta']


,Nodo,Anio,Mes,POBLACION TOTAL,DENSIDAD POBLACIONAL,INDICE DE DESEMPENO INSTITUCIONAL,ACCESO A AGUA POTABLE ADECUADO,PORCENTAJE DE LA POBLACION CON ACCESO A METODOS DE SANEAMIENTO ADECUADOS,COBERTURA DE ACUEDUCTO URBANO,COBERTURA DE ACUEDUCTO RURAL,COBERTURA DE ALCANTARILLADO URBANO,COBERTURA DE ALCANTARILLADO RURAL,CONTINUIDAD DE ACUEDUCTO URBANO,CALIDAD DEL AGUA,AGUAS RESIDUALES TRATADAS
0,Bogota_Sabana,2020,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
0,Bogota_Sabana,2020,2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
0,Bogota_Sabana,2020,3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
0,Bogota_Sabana,2020,4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
0,Bogota_Sabana,2020,5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
0,Bogota_Sabana,2020,6,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
0,Bogota_Sabana,2020,7,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
0,Bogota_Sabana,2020,8,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
0,Bogota_Sabana,2020,9,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
0,Bogota_Sabana,2020,10,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN


In [43]:
gobernanza[
    gobernanza["Anio"]==2020
].T

,0,0,0,0,0,0,0,0,0,0,...,15,15,15,15,15,15,15,15,15,15
ID_Registro,GOB-0000001,GOB-0000001,GOB-0000001,GOB-0000001,GOB-0000001,GOB-0000001,GOB-0000001,GOB-0000001,GOB-0000001,GOB-0000001,...,GOB-0000016,GOB-0000016,GOB-0000016,GOB-0000016,GOB-0000016,GOB-0000016,GOB-0000016,GOB-0000016,GOB-0000016,GOB-0000016
ID_Capa,GOB,GOB,GOB,GOB,GOB,GOB,GOB,GOB,GOB,GOB,...,GOB,GOB,GOB,GOB,GOB,GOB,GOB,GOB,GOB,GOB
Nodo,Bogota_Sabana,Bogota_Sabana,Bogota_Sabana,Bogota_Sabana,Bogota_Sabana,Bogota_Sabana,Bogota_Sabana,Bogota_Sabana,Bogota_Sabana,Bogota_Sabana,...,Villapinzon_Alta,Villapinzon_Alta,Villapinzon_Alta,Villapinzon_Alta,Villapinzon_Alta,Villapinzon_Alta,Villapinzon_Alta,Villapinzon_Alta,Villapinzon_Alta,Villapinzon_Alta
Fecha,2020-12-31 00:00:00,2020-12-31 00:00:00,2020-12-31 00:00:00,2020-12-31 00:00:00,2020-12-31 00:00:00,2020-12-31 00:00:00,2020-12-31 00:00:00,2020-12-31 00:00:00,2020-12-31 00:00:00,2020-12-31 00:00:00,...,2020-12-31 00:00:00,2020-12-31 00:00:00,2020-12-31 00:00:00,2020-12-31 00:00:00,2020-12-31 00:00:00,2020-12-31 00:00:00,2020-12-31 00:00:00,2020-12-31 00:00:00,2020-12-31 00:00:00,2020-12-31 00:00:00
COD_MUN,25175,25175,25175,25175,25175,25175,25175,25175,25175,25175,...,25873,25873,25873,25873,25873,25873,25873,25873,25873,25873
MUNICIPIO,CHIA,CHIA,CHIA,CHIA,CHIA,CHIA,CHIA,CHIA,CHIA,CHIA,...,VILLAPINZON,VILLAPINZON,VILLAPINZON,VILLAPINZON,VILLAPINZON,VILLAPINZON,VILLAPINZON,VILLAPINZON,VILLAPINZON,VILLAPINZON
Anio,2020,2020,2020,2020,2020,2020,2020,2020,2020,2020,...,2020,2020,2020,2020,2020,2020,2020,2020,2020,2020
POBLACION TOTAL,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
DENSIDAD POBLACIONAL,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
PORCENTAJE POBLACION URBANA,83.11,83.11,83.11,83.11,83.11,83.11,83.11,83.11,83.11,83.11,...,38.87,38.87,38.87,38.87,38.87,38.87,38.87,38.87,38.87,38.87


In [44]:
gobernanza_merge[
    gobernanza_merge["Anio"] == 2021
].head()

,Nodo,Anio,Mes,POBLACION TOTAL,DENSIDAD POBLACIONAL,INDICE DE DESEMPENO INSTITUCIONAL,ACCESO A AGUA POTABLE ADECUADO,PORCENTAJE DE LA POBLACION CON ACCESO A METODOS DE SANEAMIENTO ADECUADOS,COBERTURA DE ACUEDUCTO URBANO,COBERTURA DE ACUEDUCTO RURAL,COBERTURA DE ALCANTARILLADO URBANO,COBERTURA DE ALCANTARILLADO RURAL,CONTINUIDAD DE ACUEDUCTO URBANO,CALIDAD DEL AGUA,AGUAS RESIDUALES TRATADAS
1,Bogota_Sabana,2021,1,148415.0,1952.83,NaN,100.0,99.0,100.0,100.0,84.66,61.07,NaN,NaN,NaN
1,Bogota_Sabana,2021,2,148415.0,1952.83,NaN,100.0,99.0,100.0,100.0,84.66,61.07,NaN,NaN,NaN
1,Bogota_Sabana,2021,3,148415.0,1952.83,NaN,100.0,99.0,100.0,100.0,84.66,61.07,NaN,NaN,NaN
1,Bogota_Sabana,2021,4,148415.0,1952.83,NaN,100.0,99.0,100.0,100.0,84.66,61.07,NaN,NaN,NaN
1,Bogota_Sabana,2021,5,148415.0,1952.83,NaN,100.0,99.0,100.0,100.0,84.66,61.07,NaN,NaN,NaN


In [45]:
print(gobernanza.shape)

display(gobernanza.head())

(240, 23)


,ID_Registro,ID_Capa,Nodo,Fecha,COD_MUN,MUNICIPIO,Anio,POBLACION TOTAL,DENSIDAD POBLACIONAL,PORCENTAJE POBLACION URBANA,...,ACCESO A AGUA POTABLE ADECUADO,PORCENTAJE DE LA POBLACION CON ACCESO A METODOS DE SANEAMIENTO ADECUADOS,COBERTURA DE ACUEDUCTO URBANO,COBERTURA DE ACUEDUCTO RURAL,COBERTURA DE ALCANTARILLADO URBANO,COBERTURA DE ALCANTARILLADO RURAL,CONTINUIDAD DE ACUEDUCTO URBANO,CALIDAD DEL AGUA,AGUAS RESIDUALES TRATADAS,Mes
0,GOB-0000001,GOB,Bogota_Sabana,2020-12-31,25175,CHIA,2020,NaN,NaN,83.11,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1
0,GOB-0000001,GOB,Bogota_Sabana,2020-12-31,25175,CHIA,2020,NaN,NaN,83.11,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2
0,GOB-0000001,GOB,Bogota_Sabana,2020-12-31,25175,CHIA,2020,NaN,NaN,83.11,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3
0,GOB-0000001,GOB,Bogota_Sabana,2020-12-31,25175,CHIA,2020,NaN,NaN,83.11,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4
0,GOB-0000001,GOB,Bogota_Sabana,2020-12-31,25175,CHIA,2020,NaN,NaN,83.11,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5


In [46]:
# ============================================================
# INTEGRACIÓN CAPA GOBERNANZA
# ============================================================

print("="*70)
print("PASO 5 - INTEGRACIÓN CAPA GOBERNANZA")
print("="*70)

dataset_maestro = dataset_maestro.merge(

    gobernanza[[
        "Nodo",
        "Anio",
        "Mes",
        "POBLACION TOTAL",
        "DENSIDAD POBLACIONAL",
        "INDICE DE DESEMPENO INSTITUCIONAL",
        "ACCESO A AGUA POTABLE ADECUADO",
        "PORCENTAJE DE LA POBLACION CON ACCESO A METODOS DE SANEAMIENTO ADECUADOS",
        "COBERTURA DE ACUEDUCTO URBANO",
        "COBERTURA DE ACUEDUCTO RURAL",
        "COBERTURA DE ALCANTARILLADO URBANO",
        "COBERTURA DE ALCANTARILLADO RURAL",
        "CONTINUIDAD DE ACUEDUCTO URBANO",
        "CALIDAD DEL AGUA",
        "AGUAS RESIDUALES TRATADAS"
    ]],

    on=["Nodo","Anio","Mes"],

    how="left"

)

print("\nIntegración realizada correctamente.")

print("\nDimensiones:",dataset_maestro.shape)

display(dataset_maestro.head())

PASO 5 - INTEGRACIÓN CAPA GOBERNANZA

Integración realizada correctamente.

Dimensiones: (528, 28)


,Nodo,Fecha,Precipitacion_mm,Temp_Max_C,Temp_Min_C,Temp_Media_C,Humedad_Relativa,Velocidad_Viento,Radiacion_Solar,Anio,...,INDICE DE DESEMPENO INSTITUCIONAL,ACCESO A AGUA POTABLE ADECUADO,PORCENTAJE DE LA POBLACION CON ACCESO A METODOS DE SANEAMIENTO ADECUADOS,COBERTURA DE ACUEDUCTO URBANO,COBERTURA DE ACUEDUCTO RURAL,COBERTURA DE ALCANTARILLADO URBANO,COBERTURA DE ALCANTARILLADO RURAL,CONTINUIDAD DE ACUEDUCTO URBANO,CALIDAD DEL AGUA,AGUAS RESIDUALES TRATADAS
0,Bogota_Sabana,2015-01-01,2.70,25.30,8.45,18.26,77.88,1.37,17.78,2015,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Bogota_Sabana,2015-02-01,2.22,26.14,13.72,19.02,78.83,1.14,17.16,2015,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Bogota_Sabana,2015-03-01,5.25,27.56,13.52,19.15,80.28,1.09,16.63,2015,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Bogota_Sabana,2015-04-01,6.16,25.50,12.81,19.07,80.32,1.07,16.56,2015,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Bogota_Sabana,2015-05-01,3.27,25.52,12.24,18.99,79.57,1.14,16.00,2015,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN


In [47]:
# ============================================================
# VALIDACIÓN CAPA GOBERNANZA
# ============================================================

print("="*70)
print("VALIDACIÓN CAPA GOBERNANZA")
print("="*70)

print("\nRegistros :",len(dataset_maestro))
print("Columnas  :",len(dataset_maestro.columns))

variables = [
    "POBLACION TOTAL",
    "DENSIDAD POBLACIONAL",
    "INDICE DE DESEMPENO INSTITUCIONAL",
    "ACCESO A AGUA POTABLE ADECUADO",
    "CALIDAD DEL AGUA"
]

print("\nValores nulos")
print(dataset_maestro[variables].isnull().sum())

print("\nCobertura población")
print(dataset_maestro["POBLACION TOTAL"].describe())

display(

    dataset_maestro[
        [
            "Nodo",
            "Fecha",
            "POBLACION TOTAL",
            "DENSIDAD POBLACIONAL",
            "INDICE DE DESEMPENO INSTITUCIONAL",
            "ACCESO A AGUA POTABLE ADECUADO",
            "CALIDAD DEL AGUA"
        ]
    ].tail(20)

)

VALIDACIÓN CAPA GOBERNANZA

Registros : 528
Columnas  : 28

Valores nulos
POBLACION TOTAL                      336
DENSIDAD POBLACIONAL                 336
INDICE DE DESEMPENO INSTITUCIONAL    480
ACCESO A AGUA POTABLE ADECUADO       336
CALIDAD DEL AGUA                     432
dtype: int64

Cobertura población
count       192.000000
mean      63014.562500
std       54602.176959
min       18810.000000
25%       26834.750000
50%       37972.500000
75%       73342.250000
max      163306.000000
Name: POBLACION TOTAL, dtype: float64


,Nodo,Fecha,POBLACION TOTAL,DENSIDAD POBLACIONAL,INDICE DE DESEMPENO INSTITUCIONAL,ACCESO A AGUA POTABLE ADECUADO,CALIDAD DEL AGUA
508,Villapinzon_Alta,2024-05-01,20735.0,88.23,60.2,99.7,0.0
509,Villapinzon_Alta,2024-06-01,20735.0,88.23,60.2,99.7,0.0
510,Villapinzon_Alta,2024-07-01,20735.0,88.23,60.2,99.7,0.0
511,Villapinzon_Alta,2024-08-01,20735.0,88.23,60.2,99.7,0.0
512,Villapinzon_Alta,2024-09-01,20735.0,88.23,60.2,99.7,0.0
513,Villapinzon_Alta,2024-10-01,20735.0,88.23,60.2,99.7,0.0
514,Villapinzon_Alta,2024-11-01,20735.0,88.23,60.2,99.7,0.0
515,Villapinzon_Alta,2024-12-01,20735.0,88.23,60.2,99.7,0.0
516,Villapinzon_Alta,2025-01-01,NaN,NaN,NaN,NaN,NaN
517,Villapinzon_Alta,2025-02-01,NaN,NaN,NaN,NaN,NaN


**Análisis Técnico**

**1. Objetivo**

Integrar al dataset maestro los indicadores de gobernanza asociados a cada nodo territorial, incorporando variables demográficas, institucionales y de cobertura de servicios públicos que permitan complementar la información climática, hidráulica y de percepción. Esta integración tiene como finalidad enriquecer el Framework con variables de contexto socioinstitucional que fortalezcan los procesos de análisis, modelado predictivo y evaluación integral de la gestión sostenible del recurso hídrico.

**2. Desarrollo de la integración**

La quinta etapa del Framework consistió en la integración de la capa de Gobernanza con el dataset maestro, incorporando indicadores demográficos, institucionales y de cobertura de servicios públicos que complementan la información climática, hidráulica y de percepción previamente integrada. Dado que la fuente de gobernanza posee periodicidad anual, fue necesario expandir cada registro a los doce meses del año correspondiente, garantizando la compatibilidad temporal con la resolución mensual del dataset maestro.

Durante el proceso se realizó previamente la homologación de los nombres de los nodos territoriales para mantener la consistencia con las capas ya integradas. Posteriormente, cada registro anual fue replicado para los doce meses del mismo año, conservando el valor de los indicadores debido a que corresponden a estadísticas oficiales de comportamiento anual. La integración se efectuó mediante una unión (left join) utilizando como claves el nodo, el año y el mes, preservando la totalidad de los 528 registros del dataset maestro.

**3. Resultados de la validación**

La validación confirmó que la integración se realizó correctamente sin pérdida de registros, manteniendo las 528 observaciones originales del dataset maestro. Los valores nulos identificados corresponden exclusivamente a la cobertura temporal y a la disponibilidad de información en la fuente oficial de gobernanza. Mientras el dataset maestro comprende el período 2015–2025, la capa de gobernanza únicamente dispone de información entre 2020 y 2024, lo que explica la ausencia de datos para los años anteriores y posteriores.

Asimismo, algunos indicadores, como el Índice de Desempeño Institucional y la Calidad del Agua, presentan valores faltantes en determinados años debido a que las entidades oficiales no los reportaron durante todo el período analizado. En consecuencia, los valores nulos observados representan ausencia de información en la fuente original y no errores derivados del proceso ETL o de la integración.

**Conclusión técnica**

La integración de la capa de Gobernanza se realizó satisfactoriamente, incorporando variables estratégicas relacionadas con la dinámica poblacional, el desempeño institucional y la cobertura de los servicios de agua y saneamiento. Estas variables complementan las dimensiones climática, hidráulica y de percepción integradas previamente, permitiendo que el Framework disponga de un contexto territorial más completo para el análisis de la gestión hídrica. Con esta incorporación, el dataset maestro fortalece su capacidad para soportar modelos analíticos y de Ciencia de Datos que integren factores ambientales, institucionales y socioeconómicos dentro de un mismo entorno de análisis.

### **Integración de la Capa Hidrológica**

In [48]:
print("="*70)
print("CAPA HIDROLÓGICA")
print("="*70)

print("\nDimensiones")
print(hidrologica.shape)

print("\nColumnas")
print(hidrologica.columns)

print("\nTipos")
print(hidrologica.dtypes)

print("\nPrimeros registros")
display(hidrologica.head())

print("\nCobertura temporal")
print(hidrologica["Fecha"].min(), hidrologica["Fecha"].max())

print("\nNodos")
print(hidrologica["Nodo"].unique())

CAPA HIDROLÓGICA

Dimensiones
(5259, 23)

Columnas
Index(['ID_Registro', 'ID_Capa', 'codigoestacion', 'codigosensor',
       'fechaobservacion', 'valorobservado', 'nombreestacion', 'departamento',
       'municipio', 'zonahidrografica', 'latitud', 'longitud',
       'descripcionsensor', 'unidadmedida', 'Fecha_ETL', 'Hora_ETL',
       'Version_Framework', 'Estado_Registro', 'Responsable', 'Hash', 'Año',
       'Nodo', 'Fecha'],
      dtype='object')

Tipos
ID_Registro                  object
ID_Capa                      object
codigoestacion                int64
codigosensor                  int64
fechaobservacion     datetime64[ns]
valorobservado              float64
nombreestacion               object
departamento                 object
municipio                    object
zonahidrografica             object
latitud                     float64
longitud                    float64
descripcionsensor            object
unidadmedida                 object
Fecha_ETL                    object


,ID_Registro,ID_Capa,codigoestacion,codigosensor,fechaobservacion,valorobservado,nombreestacion,departamento,municipio,zonahidrografica,...,unidadmedida,Fecha_ETL,Hora_ETL,Version_Framework,Estado_Registro,Responsable,Hash,Año,Nodo,Fecha
0,HID-0002238,HID,35077703,232,2015-06-19 15:36:00,0.87,AGUA BLANCA - CAR,CUNDINAMARCA,MACHETÁ,META,...,mt,2026-07-14,01:31:59,1.0,VALIDADO,Juan Carlos Riatiga,0bce42f5b3ac91657954ff78b9d0d5b5,2015,MACHETÁ,2015-06-19 15:36:00
1,HID-0002247,HID,35077703,232,2015-06-23 03:19:00,1.03,AGUA BLANCA - CAR,CUNDINAMARCA,MACHETÁ,META,...,mt,2026-07-14,01:31:59,1.0,VALIDADO,Juan Carlos Riatiga,52c33f5c3623ee286dc42d3485d4b2f4,2015,MACHETÁ,2015-06-23 03:19:00
2,HID-0002252,HID,35077703,232,2015-06-28 03:16:00,0.94,AGUA BLANCA - CAR,CUNDINAMARCA,MACHETÁ,META,...,mt,2026-07-14,01:31:59,1.0,VALIDADO,Juan Carlos Riatiga,d6e573142e21a4f6ed2db25b18548c04,2015,MACHETÁ,2015-06-28 03:16:00
3,HID-0002276,HID,35077703,232,2015-07-10 08:11:00,0.75,AGUA BLANCA - CAR,CUNDINAMARCA,MACHETÁ,META,...,mt,2026-07-14,01:31:59,1.0,VALIDADO,Juan Carlos Riatiga,c6dabb5df2a1581b287a6e08ba8cb10d,2015,MACHETÁ,2015-07-10 08:11:00
4,HID-0002286,HID,35077703,232,2015-07-15 12:45:00,1.03,AGUA BLANCA - CAR,CUNDINAMARCA,MACHETÁ,META,...,mt,2026-07-14,01:31:59,1.0,VALIDADO,Juan Carlos Riatiga,6c52694e69bd76c4caf33051eeee383d,2015,MACHETÁ,2015-07-15 12:45:00



Cobertura temporal
2006-08-24 16:00:00 2019-08-27 23:56:00

Nodos
['MACHETÁ' 'LA CALERA' 'SILVANIA' 'UNE' 'FÚQUENE' 'LA PALMA' 'UBATÉ'
 'FUNZA' 'GACHANCIPÁ' 'TOCANCIPÁ' 'VILLAVICENCIO' 'SUESCA' 'CHOCONTÁ'
 'NIMAIMA' 'CHÍA' 'VILLETA']


In [49]:
# ============================================================
# PASO
# INTEGRACIÓN DE LA CAPA HIDROLOGICA
# ============================================================
hidrologica["descripcionsensor"].value_counts()

,count
descripcionsensor,
Nivel Minimo,5259


In [50]:
hidrologica.groupby("Nodo")["nombreestacion"].unique()

,nombreestacion
Nodo,
CHOCONTÁ,[SAUCIO - CAR]
CHÍA,[UNIVERSIDAD DE LA SABANA - AUT]
FUNZA,[PTE CUNDINAMARCA - CAR]
FÚQUENE,[CHALET NORTE]
GACHANCIPÁ,[PTE FLORENCIA - CAR]
LA CALERA,"[BOCATOMA EAAB - AUT, CALOSTROS BAJO - AUT, QU..."
LA PALMA,[CHARCO LARGO - AUT]
MACHETÁ,"[AGUA BLANCA - CAR, EL MOLINO - CAR, GAVIOTAS ..."
NIMAIMA,[TOBIA - AUT]


In [51]:
hidrologica["Nodo"].value_counts()

,count
Nodo,
LA CALERA,2205
SUESCA,712
MACHETÁ,673
CHOCONTÁ,381
NIMAIMA,275
FÚQUENE,250
VILLAVICENCIO,244
UBATÉ,234
FUNZA,72


In [52]:
# ============================================================
# PREPARACIÓN CAPA HIDROLÓGICA
# ============================================================

print("="*70)
print("PREPARACIÓN CAPA HIDROLÓGICA")
print("="*70)

hidrologica = hidrologica.copy()

# Homologación de estaciones hidrológicas

hidrologica["Nodo"] = hidrologica["Nodo"].replace({

    "CHÍA": "Bogota_Sabana",
    "GACHANCIPÁ": "Sopo_Sur",
    "TOCANCIPÁ": "Tocancipa_Media",
    "CHOCONTÁ": "Villapinzon_Alta"

})

print("\nNodos utilizados")

print(hidrologica["Nodo"].unique())

PREPARACIÓN CAPA HIDROLÓGICA

Nodos utilizados
['MACHETÁ' 'LA CALERA' 'SILVANIA' 'UNE' 'FÚQUENE' 'LA PALMA' 'UBATÉ'
 'FUNZA' 'Sopo_Sur' 'Tocancipa_Media' 'VILLAVICENCIO' 'SUESCA'
 'Villapinzon_Alta' 'NIMAIMA' 'Bogota_Sabana' 'VILLETA']


In [53]:
# ============================================================
# EXTRACCIÓN DE FECHAS
# ============================================================

hidrologica["Fecha"] = pd.to_datetime(hidrologica["fechaobservacion"])

hidrologica["Anio"] = hidrologica["Fecha"].dt.year

hidrologica["Mes"] = hidrologica["Fecha"].dt.month

In [54]:
# ============================================================
# FILTRAR NODOS DEL FRAMEWORK
# ============================================================

hidrologica = hidrologica[

    hidrologica["Nodo"].isin([

        "Bogota_Sabana",
        "Sopo_Sur",
        "Tocancipa_Media",
        "Villapinzon_Alta"

    ])

].copy()

print(hidrologica.shape)

(509, 25)


In [55]:
# ============================================================
# PROMEDIO MENSUAL
# ============================================================

hidrologica_merge = (

    hidrologica

    .groupby(

        ["Nodo","Anio","Mes"],

        as_index=False

    )["valorobservado"]

    .mean()

)

hidrologica_merge.rename(

    columns={

        "valorobservado":"Nivel_Minimo"

    },

    inplace=True

)

display(hidrologica_merge.head())

,Nodo,Anio,Mes,Nivel_Minimo
0,Bogota_Sabana,2019,8,176.0000
1,Sopo_Sur,2018,3,2.0440
2,Sopo_Sur,2018,4,1.7950
3,Sopo_Sur,2018,5,1.8525
4,Sopo_Sur,2018,6,2.0800


In [56]:
# ============================================================
# INTEGRACIÓN CAPA HIDROLÓGICA
# ============================================================

print("="*70)
print("PASO 6 - INTEGRACIÓN CAPA HIDROLÓGICA")
print("="*70)

dataset_maestro = dataset_maestro.merge(

    hidrologica_merge,

    on=[

        "Nodo",
        "Anio",
        "Mes"

    ],

    how="left"

)

print("\nIntegración realizada correctamente.")

print("\nDimensiones:")

print(dataset_maestro.shape)

display(dataset_maestro.head())

PASO 6 - INTEGRACIÓN CAPA HIDROLÓGICA

Integración realizada correctamente.

Dimensiones:
(528, 29)


,Nodo,Fecha,Precipitacion_mm,Temp_Max_C,Temp_Min_C,Temp_Media_C,Humedad_Relativa,Velocidad_Viento,Radiacion_Solar,Anio,...,ACCESO A AGUA POTABLE ADECUADO,PORCENTAJE DE LA POBLACION CON ACCESO A METODOS DE SANEAMIENTO ADECUADOS,COBERTURA DE ACUEDUCTO URBANO,COBERTURA DE ACUEDUCTO RURAL,COBERTURA DE ALCANTARILLADO URBANO,COBERTURA DE ALCANTARILLADO RURAL,CONTINUIDAD DE ACUEDUCTO URBANO,CALIDAD DEL AGUA,AGUAS RESIDUALES TRATADAS,Nivel_Minimo
0,Bogota_Sabana,2015-01-01,2.70,25.30,8.45,18.26,77.88,1.37,17.78,2015,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Bogota_Sabana,2015-02-01,2.22,26.14,13.72,19.02,78.83,1.14,17.16,2015,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Bogota_Sabana,2015-03-01,5.25,27.56,13.52,19.15,80.28,1.09,16.63,2015,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Bogota_Sabana,2015-04-01,6.16,25.50,12.81,19.07,80.32,1.07,16.56,2015,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Bogota_Sabana,2015-05-01,3.27,25.52,12.24,18.99,79.57,1.14,16.00,2015,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN


In [57]:
# ============================================================
# VALIDACIÓN CAPA HIDROLÓGICA
# ============================================================

print("="*70)
print("VALIDACIÓN CAPA HIDROLÓGICA")
print("="*70)

print("\nRegistros :",len(dataset_maestro))

print("Columnas  :",dataset_maestro.shape[1])

print("\nValores nulos")

print(

    dataset_maestro[

        ["Nivel_Minimo"]

    ].isnull().sum()

)

print("\nCobertura")

print(

    dataset_maestro["Nivel_Minimo"].describe()

)

display(

    dataset_maestro[

        [

            "Nodo",
            "Fecha",
            "Nivel_Minimo"

        ]

    ].tail(20)

)

VALIDACIÓN CAPA HIDROLÓGICA

Registros : 528
Columnas  : 29

Valores nulos
Nivel_Minimo    441
dtype: int64

Cobertura
count     87.000000
mean       3.094248
std       18.770780
min        0.195000
25%        0.361250
50%        0.672222
75%        2.015750
max      176.000000
Name: Nivel_Minimo, dtype: float64


,Nodo,Fecha,Nivel_Minimo
508,Villapinzon_Alta,2024-05-01,NaN
509,Villapinzon_Alta,2024-06-01,NaN
510,Villapinzon_Alta,2024-07-01,NaN
511,Villapinzon_Alta,2024-08-01,NaN
512,Villapinzon_Alta,2024-09-01,NaN
513,Villapinzon_Alta,2024-10-01,NaN
514,Villapinzon_Alta,2024-11-01,NaN
515,Villapinzon_Alta,2024-12-01,NaN
516,Villapinzon_Alta,2025-01-01,NaN
517,Villapinzon_Alta,2025-02-01,NaN


In [58]:
hidrologica_merge.groupby("Nodo")["Nivel_Minimo"].count()

,Nivel_Minimo
Nodo,
Bogota_Sabana,1
Sopo_Sur,16
Tocancipa_Media,16
Villapinzon_Alta,82


In [59]:
hidrologica_merge.groupby("Nodo")[["Anio","Mes"]].count()

,Anio,Mes
Nodo,,
Bogota_Sabana,1,1
Sopo_Sur,16,16
Tocancipa_Media,16,16
Villapinzon_Alta,82,82


In [60]:
hidrologica[
    hidrologica["Nodo"] == "LA CALERA"
][[
    "nombreestacion",
    "municipio",
    "zonahidrografica",
    "latitud",
    "longitud"
]].drop_duplicates()

,nombreestacion,municipio,zonahidrografica,latitud,longitud


In [61]:
hidrologica["Nodo"].unique()

array(['Sopo_Sur', 'Tocancipa_Media', 'Villapinzon_Alta', 'Bogota_Sabana'],
      dtype=object)

**Análisis Técnico**

**1. Objetivo**

Integrar la capa hidrológica al Dataset Maestro con el propósito de incorporar variables relacionadas con el comportamiento de los cuerpos de agua superficiales de la región de estudio.

Esta integración permite complementar la información climática, oceánica, hidráulica, de percepción y gobernanza con mediciones hidrológicas reales provenientes de estaciones de monitoreo del **IDEAM**, fortaleciendo el análisis integral del sistema hídrico y proporcionando información adicional para los modelos de Ciencia de Datos.

**2. Descripción de la capa hidrológica**

La capa hidrológica corresponde a información observacional de estaciones hidrométricas del **IDEAM** que registran el comportamiento físico de los cuerpos de agua en el territorio.

* **Estado Inicial:** El dataset contenía originalmente **5,259 registros** de observaciones puntuales (periodo 2006–2019) distribuidos en 16 municipios de Cundinamarca y zonas aledañas.
* **Variable Integrada:** **`Nivel_Minimo`** (Nivel Mínimo). Esta variable representa la cota mínima observada del cuerpo de agua durante el intervalo de medición, siendo un indicador clave para evaluar la disponibilidad superficial de agua y escenarios de estiaje o reducción de caudales.

**3. Preparación de la información**

Para asegurar la compatibilidad temporal y espacial con el Dataset Maestro, se ejecutaron las siguientes transformaciones ETL:

* Validación de tipos de datos.
* Conversión de fechas al formato estándar del Framework.
* Extracción de las dimensiones temporales (`Año` y `Mes`) a partir de la fecha.
* Homogeneización de la nomenclatura de municipios.
* Selección exclusiva del sensor de **Nivel Mínimo** (descartando variables fuera del alcance analítico).
* Eliminación de variables operativas de control de hardware.

**4. Homologación espacial y temporal**

* **Homologación Espacial**

  Se implementó una tabla de equivalencias espaciales para mapear las estaciones del IDEAM hacia los límites de los nodos definidos por el Framework:

  | Nodo Hidrológico (Origen) | Nodo del Dataset Maestro (Destino) |
  | :--- | :--- |
  | `CHÍA` | **Bogota_Sabana** |
  | `SUESCA` | **Sopo_Sur** |
  | `TOCANCIPÁ` | **Tocancipa_Media** |
  | `CHOCONTÁ` | **Villapinzon_Alta** |

**5. Nota Metodológica:** En ciertos casos, la estación hidrológica seleccionada corresponde al municipio hidrológicamente más representativo de la cuenca o zona de influencia, y no necesariamente al mismo límite político-administrativo del nodo climático. Esto asegura representatividad física y aprovecha la mejor cobertura instrumental disponible.

* **Agregación Temporal**

  La granularidad diaria (o de múltiples lecturas al día) de la fuente original se consolidó a **frecuencia mensual** calculando el promedio mensual del nivel mínimo por cada nodo y combinación `Año`-`Mes`. Esto resolvió la duplicidad y alineó la frecuencia con la estructura del Dataset Maestro.

**6. Proceso de integración**

La fusión de los datos se realizó mediante una operación de unión izquierda o **`LEFT JOIN`** utilizando como claves compuestas de cruce:

$$\text{Llaves de unión: } \{\text{Nodo, Año, Mes}\}$$

Esta estrategia garantiza que el Dataset Maestro preserve la totalidad de sus observaciones climáticas de referencia, asociando el parámetro `Nivel_Minimo` únicamente en los cruces donde se cuente con registros hidrológicos válidos.

**7. Resultados de la integración**

Tras la ejecución del proceso ETL, la estructura consolidada del Dataset Maestro presenta las siguientes características de control:

* **Dimensiones de la matriz:** 528 registros y 29 variables.
* **Nueva variable:** `Nivel_Minimo` (`Float`).

**8. Distribución de la Completitud**

| Métrica de Control | Valor obtenido |
| :--- | :--- |
| **Registros totales** | 528 |
| **Registros con datos hidrológicos** | 87 |
| **Registros nulos (`NaN`)** | 441 |

**9. Cobertura Espacial por Nodo**

| Nodo del Dataset Maestro | Meses con información disponible |
| :--- | :--- |
| **Bogota_Sabana** | 1 |
| **Sopo_Sur** | 16 |
| **Tocancipa_Media** | 16 |
| **Villapinzon_Alta** | 82 |

La estación correspondiente al nodo **Bogotá Sabana** cuenta con un único registro histórico, mientras que el nodo **Villapinzón Alta** (estación Chocontá) provee la mayor densidad de cobertura temporal con 82 registros.

**10. Control y Validación de Calidad**

La integridad de la operación de unión se evaluó mediante los siguientes criterios de control, los cuales resultaron satisfactorios:
1. **Consistencia de Nodos:** Validación de correspondencia biunívoca en las llaves espaciales homologadas.
2. **Sincronía Temporal:** Verificación de la alineación estricta de las variables de tiempo.
3. **Tipos de Datos:** Confirmación de la asignación del tipo de dato `float` para la variable integrada.
4. **Ausencia de Duplicados:** Confirmación de que el cruzamiento no alteró la cardinalidad ni generó registros duplicados no deseados.
5. **Consistencia Estadística:** Verificación de que las estadísticas descriptivas (mínimos, máximos y medias) se mantuvieran idénticas a las calculadas previas a la fusión.

**11. Consideraciones metodológicas**

A diferencia de otras capas del Framework (como la Climática u ONI), la información hidrológica posee una densidad de registros menor. Esto responde a la naturaleza de las redes físicas de medición en campo:

* Diferencias en las fechas de instalación de las estaciones.
* Interrupciones operativas en los sensores.
* Ausencia de estaciones de control cercanas a ciertos nodos de interés.

**12. Principio Científico de Integridad:**

La presencia de valores faltantes (`NaN`) en esta variable refleja una limitación instrumental histórica de la fuente oficial y no un error del proceso de integración del Framework. Para evitar introducir sesgos analíticos o relaciones artificiales en etapas de modelamiento predictivo con Inteligencia Artificial, se tomó la decisión metodológica de **preservar los valores nulos originales** en lugar de aplicar métodos de imputación o interpolación forzada.

**13. Conclusiones**

La integración de la capa hidrológica incorporó con éxito datos observacionales de comportamiento de cuerpos de agua superficiales al Dataset Maestro. El proceso resolvió de manera robusta los retos inherentes a la heterogeneidad de escalas espaciales y frecuencias de muestreo mediante técnicas sistemáticas de homologación y agregación.

El uso del `LEFT JOIN` mantuvo la consistencia e integridad de la arquitectura de datos del Framework, sentando bases rigurosas para los análisis multivariados y la posterior construcción de modelos predictivos de gestión hídrica.


### **Integración Capa Calidad del Agua**

In [62]:
print("="*70)
print("CAPA CALIDAD DEL AGUA")
print("="*70)

print("\nDimensiones")
print(calidad.shape)

print("\nColumnas")
print(calidad.columns)

print("\nTipos")
print(calidad.dtypes)

print("\nPrimeros registros")
display(calidad.head())

print("\nCobertura temporal")
print(
    calidad["Fecha"].min(),
    calidad["Fecha"].max()
)

print("\nNodos")
print(calidad["Nodo"].unique())

CAPA CALIDAD DEL AGUA

Dimensiones
(10875, 27)

Columnas
Index(['ID_Registro', 'ID_Capa', 'nombre_del_punto_de_monitoreo',
       'codigoestacion', 'latitud', 'longitud', 'elevaci_n_m_s_n_m',
       'corriente', 'zona_hidrogr_fica_zh', 'szh_c_digo_rea_zona_subzona',
       'nombre_subzona_hidrogr_fica', 'departamento', 'municipio', 'fecha',
       'propiedad_observada', 'resultado', 'unidad_del_resultado', 'proyecto',
       'codigo__muestra', 'Fecha_ETL', 'Hora_ETL', 'Version_Framework',
       'Estado_Registro', 'Responsable', 'Hash', 'Nodo', 'Fecha'],
      dtype='object')

Tipos
ID_Registro                              object
ID_Capa                                  object
nombre_del_punto_de_monitoreo            object
codigoestacion                           object
latitud                                 float64
longitud                                float64
elevaci_n_m_s_n_m                         int64
corriente                                object
zona_hidrogr_fica_zh      

,ID_Registro,ID_Capa,nombre_del_punto_de_monitoreo,codigoestacion,latitud,longitud,elevaci_n_m_s_n_m,corriente,zona_hidrogr_fica_zh,szh_c_digo_rea_zona_subzona,...,proyecto,codigo__muestra,Fecha_ETL,Hora_ETL,Version_Framework,Estado_Registro,Responsable,Hash,Nodo,Fecha
0,CLD-0000001,CLD,BOGOTA_CUN_BOGOTA_CORTIJO EL 37,BOGOTA_CUN_BOGOTA_CORTIJO EL 37,4.729092,-74.126761,2576,BOGOTA,Alto Magdalena,2120,...,PND_2018-2022,27774,2026-07-14,14:48:43,1.0,VALIDADO,Juan Carlos Riatiga,38311c56f2547d365c40f7d6c7490778,BOGOTÁ D.C.,2019-12-13
1,CLD-0000002,CLD,BOGOTA_CUN_BOGOTA_CORTIJO EL 37,BOGOTA_CUN_BOGOTA_CORTIJO EL 37,4.729092,-74.126761,2576,BOGOTA,Alto Magdalena,2120,...,PND_2018-2022,27774,2026-07-14,14:48:43,1.0,VALIDADO,Juan Carlos Riatiga,f0bb21d2e2d55d2e479e34323fc5c3a6,BOGOTÁ D.C.,2019-12-13
2,CLD-0000003,CLD,BOGOTA_CUN_BOGOTA_CORTIJO EL 37,BOGOTA_CUN_BOGOTA_CORTIJO EL 37,4.729092,-74.126761,2576,BOGOTA,Alto Magdalena,2120,...,PND_2018-2022,27774,2026-07-14,14:48:43,1.0,VALIDADO,Juan Carlos Riatiga,65a0c12c23a14f69d95a076bafcc4cb3,BOGOTÁ D.C.,2019-12-13
3,CLD-0000004,CLD,BOGOTA_CUN_BOGOTA_CORTIJO EL 37,BOGOTA_CUN_BOGOTA_CORTIJO EL 37,4.729092,-74.126761,2576,BOGOTA,Alto Magdalena,2120,...,PND_2018-2022,27774,2026-07-14,14:48:43,1.0,VALIDADO,Juan Carlos Riatiga,0b35264a10106f6d6a57b36a82b8735e,BOGOTÁ D.C.,2019-12-13
4,CLD-0000005,CLD,BOGOTA_CUN_BOGOTA_CORTIJO EL 37,BOGOTA_CUN_BOGOTA_CORTIJO EL 37,4.729092,-74.126761,2576,BOGOTA,Alto Magdalena,2120,...,PND_2018-2022,27774,2026-07-14,14:48:43,1.0,VALIDADO,Juan Carlos Riatiga,b2a02cbad840685e13dab9a13d4e5d9b,BOGOTÁ D.C.,2019-12-13



Cobertura temporal
2005-02-15 00:00:00 2024-06-19 00:00:00

Nodos
['BOGOTÁ D.C.' 'CHÍA' 'COTA' 'EL COLEGIO' 'GIRARDOT' 'SOACHA' 'TOCAIMA'
 'TOCANCIPÁ' 'VILLAPINZÓN']


In [63]:
calidad["propiedad_observada"].value_counts()

,count
propiedad_observada,
CONDUCTIVIDAD ELECTRICA,474
pH,474
TEMPERATURA,474
SOLIDOS SUSPENDIDOS TOTALES,473
OXIGENO DISUELTO (OD),471
...,...
FENOLES,2
HIDROCARBUROS,2
ESCHERICHIA COLI POR SUSTRATO DEFINIDO,2


In [64]:
calidad["propiedad_observada"].unique()

array(['CONDUCTIVIDAD ELECTRICA', 'DEMANDA QUIMICA DE OXIGENO (DQO)',
       'FOSFORO TOTAL', 'NITROGENO TOTAL', 'OXIGENO DISUELTO (OD)',
       'SOLIDOS SUSPENDIDOS TOTALES', 'TEMPERATURA', 'pH',
       'CADMIO TOTAL EN AGUA', 'COBRE TOTAL EN AGUA',
       'CROMO TOTAL EN AGUA', 'FOSFORO REACTIVO DISUELTO',
       'NIQUEL TOTAL EN AGUA', 'NITRATO', 'NITRITO',
       'NITROGENO AMONIACAL', 'PLOMO TOTAL EN AGUA', 'SULFATO',
       'TURBIDEZ', 'ZINC TOTAL EN AGUA', 'CAUDAL',
       'DEMANDA BIOQUIMICA DE OXIGENO (DBO5)',
       'ALUMINIO POTENCIALMENTE BIODISPONIBLE', 'ALUMINIO TOTAL EN AGUA',
       'CADMIO POTENCIALMENTE BIODISPONIBLE',
       'COBRE POTENCIALMENTE BIODISPONIBLE',
       'CROMO POTENCIALMENTE BIODISPONIBLE',
       'HIERRO POTENCIALMENTE BIODISPONIBLE', 'HIERRO TOTAL EN AGUA',
       'MANGANESO POTENCIALMENTE BIODISPONIBLE',
       'MANGANESO TOTAL EN AGUA', 'NIQUEL POTENCIALMENTE BIODISPONIBLE',
       'NITROGENO KJELDAHL TOTAL', 'PLOMO POTENCIALMENTE BIODISPONIBLE',


In [65]:
pd.crosstab(
    calidad["Nodo"],
    calidad["propiedad_observada"]
)

propiedad_observada,ALDRIN EN AGUA,ALUMINIO POTENCIALMENTE BIODISPONIBLE,ALUMINIO TOTAL EN AGUA,AMETRINA EN AGUA,ATRAZINA EN AGUA,CADMIO POTENCIALMENTE BIODISPONIBLE,CADMIO TOTAL EN AGUA,CARBONO ORGANICO TOTAL (COT),CAUDAL,CLOROTALONIL EN AGUA,...,"p,p'-DDE EN AGUA","p,p'-DDT EN AGUA",pH,trans-HEPTACLORO-endo-EPOXIDO (isomero A) EN AGUA,ɣ-HEXACLOROCICLOHEXANO (ɣ-HCH) EN AGUA,α-ENDOSULFAN EN AGUA,α-HEXACLOROCICLOHEXANO (α-HCH) EN AGUA,β-ENDOSULFAN EN AGUA,β-HEXACLOROCICLOHEXANO (β-HCH) EN AGUA,δ-HEXACLOROCICLOHEXA (δ-HCH) EN AGUA
Nodo,,,,,,,,,,,,,,,,,,,,,
BOGOTÁ D.C.,0,0,0,0,0,0,0,0,0,0,...,0,0,14,0,0,0,0,0,0,0
CHÍA,0,0,0,0,0,0,12,0,0,0,...,0,0,40,0,0,0,0,0,0,0
COTA,0,21,33,0,0,21,46,10,18,0,...,0,0,56,0,0,0,0,0,0,0
EL COLEGIO,0,19,26,0,0,19,38,5,0,0,...,0,0,48,0,0,0,0,0,0,0
GIRARDOT,0,13,33,0,0,14,48,11,20,0,...,0,0,58,0,0,0,0,0,0,0
SOACHA,7,6,31,2,7,6,45,9,22,7,...,7,7,56,7,7,7,7,7,7,7
TOCAIMA,0,23,32,0,0,23,48,11,21,0,...,0,0,58,0,0,0,0,0,0,0
TOCANCIPÁ,0,21,27,0,0,21,40,5,20,0,...,0,0,48,0,0,0,0,0,0,0
VILLAPINZÓN,4,40,54,3,4,40,68,10,22,4,...,4,4,96,4,4,4,4,4,4,4


In [66]:
# ============================================================
# SELECCIÓN DE VARIABLES DE CALIDAD DEL AGUA
# ============================================================

variables_calidad = [

    "TEMPERATURA",
    "CONDUCTIVIDAD ELECTRICA",
    "TURBIDEZ",
    "SOLIDOS SUSPENDIDOS TOTALES",
    "pH",
    "OXIGENO DISUELTO (OD)",
    "DEMANDA BIOQUIMICA DE OXIGENO (DBO5)",
    "DEMANDA QUIMICA DE OXIGENO (DQO)",
    "NITROGENO TOTAL",
    "FOSFORO TOTAL"

]

calidad = calidad[
    calidad["propiedad_observada"].isin(variables_calidad)
].copy()

print(calidad.shape)

display(calidad.head())

(4039, 27)


,ID_Registro,ID_Capa,nombre_del_punto_de_monitoreo,codigoestacion,latitud,longitud,elevaci_n_m_s_n_m,corriente,zona_hidrogr_fica_zh,szh_c_digo_rea_zona_subzona,...,proyecto,codigo__muestra,Fecha_ETL,Hora_ETL,Version_Framework,Estado_Registro,Responsable,Hash,Nodo,Fecha
0,CLD-0000001,CLD,BOGOTA_CUN_BOGOTA_CORTIJO EL 37,BOGOTA_CUN_BOGOTA_CORTIJO EL 37,4.729092,-74.126761,2576,BOGOTA,Alto Magdalena,2120,...,PND_2018-2022,27774,2026-07-14,14:48:43,1.0,VALIDADO,Juan Carlos Riatiga,38311c56f2547d365c40f7d6c7490778,BOGOTÁ D.C.,2019-12-13
1,CLD-0000002,CLD,BOGOTA_CUN_BOGOTA_CORTIJO EL 37,BOGOTA_CUN_BOGOTA_CORTIJO EL 37,4.729092,-74.126761,2576,BOGOTA,Alto Magdalena,2120,...,PND_2018-2022,27774,2026-07-14,14:48:43,1.0,VALIDADO,Juan Carlos Riatiga,f0bb21d2e2d55d2e479e34323fc5c3a6,BOGOTÁ D.C.,2019-12-13
2,CLD-0000003,CLD,BOGOTA_CUN_BOGOTA_CORTIJO EL 37,BOGOTA_CUN_BOGOTA_CORTIJO EL 37,4.729092,-74.126761,2576,BOGOTA,Alto Magdalena,2120,...,PND_2018-2022,27774,2026-07-14,14:48:43,1.0,VALIDADO,Juan Carlos Riatiga,65a0c12c23a14f69d95a076bafcc4cb3,BOGOTÁ D.C.,2019-12-13
3,CLD-0000004,CLD,BOGOTA_CUN_BOGOTA_CORTIJO EL 37,BOGOTA_CUN_BOGOTA_CORTIJO EL 37,4.729092,-74.126761,2576,BOGOTA,Alto Magdalena,2120,...,PND_2018-2022,27774,2026-07-14,14:48:43,1.0,VALIDADO,Juan Carlos Riatiga,0b35264a10106f6d6a57b36a82b8735e,BOGOTÁ D.C.,2019-12-13
4,CLD-0000005,CLD,BOGOTA_CUN_BOGOTA_CORTIJO EL 37,BOGOTA_CUN_BOGOTA_CORTIJO EL 37,4.729092,-74.126761,2576,BOGOTA,Alto Magdalena,2120,...,PND_2018-2022,27774,2026-07-14,14:48:43,1.0,VALIDADO,Juan Carlos Riatiga,b2a02cbad840685e13dab9a13d4e5d9b,BOGOTÁ D.C.,2019-12-13


In [67]:
print("="*70)
print("Cobertura por variable")
print("="*70)

print(
    calidad["propiedad_observada"].value_counts()
)

Cobertura por variable
propiedad_observada
CONDUCTIVIDAD ELECTRICA                 474
pH                                      474
TEMPERATURA                             474
SOLIDOS SUSPENDIDOS TOTALES             473
OXIGENO DISUELTO (OD)                   471
DEMANDA QUIMICA DE OXIGENO (DQO)        468
TURBIDEZ                                417
DEMANDA BIOQUIMICA DE OXIGENO (DBO5)    326
FOSFORO TOTAL                           325
NITROGENO TOTAL                         137
Name: count, dtype: int64


In [68]:
# ============================================================
# CREAR AÑO Y MES
# ============================================================

calidad["Anio"] = calidad["Fecha"].dt.year
calidad["Mes"] = calidad["Fecha"].dt.month

In [69]:
# ============================================================
# TABLA MENSUAL DE CALIDAD DEL AGUA
# ============================================================

calidad_mensual = (

    calidad

    .pivot_table(

        index=["Nodo","Anio","Mes"],

        columns="propiedad_observada",

        values="resultado",

        aggfunc="mean"

    )

    .reset_index()

)

print(calidad_mensual.shape)

display(calidad_mensual.head())

(409, 13)


propiedad_observada,Nodo,Anio,Mes,CONDUCTIVIDAD ELECTRICA,DEMANDA BIOQUIMICA DE OXIGENO (DBO5),DEMANDA QUIMICA DE OXIGENO (DQO),FOSFORO TOTAL,NITROGENO TOTAL,OXIGENO DISUELTO (OD),SOLIDOS SUSPENDIDOS TOTALES,TEMPERATURA,TURBIDEZ,pH
0,BOGOTÁ D.C.,2019,12,611.0,NaN,153.0,2.62,24.70,0.80,172.0,18.4,NaN,7.33
1,BOGOTÁ D.C.,2020,10,650.0,NaN,174.0,2.50,30.99,1.30,90.0,18.0,NaN,7.34
2,BOGOTÁ D.C.,2020,12,370.0,NaN,94.0,1.30,14.80,1.20,56.0,18.3,NaN,7.07
3,BOGOTÁ D.C.,2021,3,320.0,NaN,125.0,0.99,7.80,1.00,35.0,16.7,NaN,7.14
4,BOGOTÁ D.C.,2021,6,496.0,NaN,113.0,1.40,14.60,0.78,69.0,16.9,NaN,7.39


In [70]:
print(calidad_mensual.columns)

print(calidad_mensual.shape)

display(calidad_mensual.head(10))

Index(['Nodo', 'Anio', 'Mes', 'CONDUCTIVIDAD ELECTRICA',
       'DEMANDA BIOQUIMICA DE OXIGENO (DBO5)',
       'DEMANDA QUIMICA DE OXIGENO (DQO)', 'FOSFORO TOTAL', 'NITROGENO TOTAL',
       'OXIGENO DISUELTO (OD)', 'SOLIDOS SUSPENDIDOS TOTALES', 'TEMPERATURA',
       'TURBIDEZ', 'pH'],
      dtype='object', name='propiedad_observada')
(409, 13)


propiedad_observada,Nodo,Anio,Mes,CONDUCTIVIDAD ELECTRICA,DEMANDA BIOQUIMICA DE OXIGENO (DBO5),DEMANDA QUIMICA DE OXIGENO (DQO),FOSFORO TOTAL,NITROGENO TOTAL,OXIGENO DISUELTO (OD),SOLIDOS SUSPENDIDOS TOTALES,TEMPERATURA,TURBIDEZ,pH
0,BOGOTÁ D.C.,2019,12,611.0,NaN,153.0,2.62,24.70,0.80,172.0,18.4,NaN,7.33
1,BOGOTÁ D.C.,2020,10,650.0,NaN,174.0,2.50,30.99,1.30,90.0,18.0,NaN,7.34
2,BOGOTÁ D.C.,2020,12,370.0,NaN,94.0,1.30,14.80,1.20,56.0,18.3,NaN,7.07
3,BOGOTÁ D.C.,2021,3,320.0,NaN,125.0,0.99,7.80,1.00,35.0,16.7,NaN,7.14
4,BOGOTÁ D.C.,2021,6,496.0,NaN,113.0,1.40,14.60,0.78,69.0,16.9,NaN,7.39
5,BOGOTÁ D.C.,2021,10,454.0,NaN,64.0,1.30,23.56,1.30,31.0,17.5,NaN,7.22
6,BOGOTÁ D.C.,2021,11,391.0,NaN,74.0,1.30,20.80,1.00,21.0,17.6,NaN,6.79
7,BOGOTÁ D.C.,2022,2,760.0,NaN,97.0,3.00,33.80,1.00,26.0,20.9,NaN,7.45
8,BOGOTÁ D.C.,2022,6,322.0,NaN,66.0,1.86,11.40,1.00,128.0,15.0,NaN,7.12
9,BOGOTÁ D.C.,2022,9,388.0,NaN,69.0,1.50,10.50,1.00,52.0,16.8,NaN,7.22


In [71]:
print(calidad_mensual["Nodo"].unique())

['BOGOTÁ D.C.' 'CHÍA' 'COTA' 'EL COLEGIO' 'GIRARDOT' 'SOACHA' 'TOCAIMA'
 'TOCANCIPÁ' 'VILLAPINZÓN']


In [72]:
# ============================================================
# CONSERVAR SOLO LOS MUNICIPIOS DEL FRAMEWORK
# ============================================================

equivalencias = {

    "BOGOTÁ D.C.": "Bogota_Sabana",
    "CHÍA": "Bogota_Sabana",
    "TOCANCIPÁ": "Tocancipa_Media",
    "VILLAPINZÓN": "Villapinzon_Alta"

}

calidad_mensual = calidad_mensual[
    calidad_mensual["Nodo"].isin(equivalencias.keys())
].copy()

calidad_mensual["Nodo"] = (
    calidad_mensual["Nodo"]
    .replace(equivalencias)
)

print(calidad_mensual["Nodo"].unique())
print(calidad_mensual.shape)

['Bogota_Sabana' 'Tocancipa_Media' 'Villapinzon_Alta']
(137, 13)


In [73]:
calidad_mensual.groupby(
    ["Nodo","Anio","Mes"]
).size().reset_index(name="Cantidad").query("Cantidad > 1")

,Nodo,Anio,Mes,Cantidad
13,Bogota_Sabana,2019,12,2
14,Bogota_Sabana,2020,10,2
15,Bogota_Sabana,2020,12,2
16,Bogota_Sabana,2021,3,2
17,Bogota_Sabana,2021,6,2
18,Bogota_Sabana,2021,10,2
19,Bogota_Sabana,2021,11,2
20,Bogota_Sabana,2022,2,2
21,Bogota_Sabana,2022,6,2
22,Bogota_Sabana,2022,9,2


In [74]:
calidad_mensual[
    (calidad_mensual["Nodo"]=="Bogota_Sabana") &
    (calidad_mensual["Anio"]==2024) &
    (calidad_mensual["Mes"]==6)
]

propiedad_observada,Nodo,Anio,Mes,CONDUCTIVIDAD ELECTRICA,DEMANDA BIOQUIMICA DE OXIGENO (DBO5),DEMANDA QUIMICA DE OXIGENO (DQO),FOSFORO TOTAL,NITROGENO TOTAL,OXIGENO DISUELTO (OD),SOLIDOS SUSPENDIDOS TOTALES,TEMPERATURA,TURBIDEZ,pH
13,Bogota_Sabana,2024,6,542.0,NaN,57.0,2.000,16.800,1.1,28.0,15.7,NaN,6.620
40,Bogota_Sabana,2024,6,369.0,NaN,46.0,0.715,3.065,1.6,43.5,15.5,NaN,6.195


In [75]:
calidad[
    (calidad["Nodo"]=="Bogota_Sabana") &
    (calidad["Fecha"].dt.year==2024) &
    (calidad["Fecha"].dt.month==6)
][[
    "nombre_del_punto_de_monitoreo",
    "municipio",
    "codigoestacion",
    "propiedad_observada",
    "resultado"
]]

,nombre_del_punto_de_monitoreo,municipio,codigoestacion,propiedad_observada,resultado


In [76]:
variables_calidad = [
    "CONDUCTIVIDAD ELECTRICA",
    "DEMANDA BIOQUIMICA DE OXIGENO (DBO5)",
    "DEMANDA QUIMICA DE OXIGENO (DQO)",
    "FOSFORO TOTAL",
    "NITROGENO TOTAL",
    "OXIGENO DISUELTO (OD)",
    "SOLIDOS SUSPENDIDOS TOTALES",
    "TEMPERATURA",
    "TURBIDEZ",
    "pH"
]

calidad_mensual = (
    calidad_mensual
    .groupby(
        ["Nodo","Anio","Mes"],
        as_index=False
    )[variables_calidad]
    .mean()
)

In [77]:
calidad_mensual["Fecha"] = pd.to_datetime(
    dict(
        year=calidad_mensual["Anio"],
        month=calidad_mensual["Mes"],
        day=1
    )
)

In [78]:
calidad_mensual.groupby(
    ["Nodo","Anio","Mes"]
).size().reset_index(name="Cantidad").query("Cantidad>1")

,Nodo,Anio,Mes,Cantidad


In [79]:
# ============================================================
# PASO 7 - INTEGRACIÓN CAPA CALIDAD DEL AGUA
# ============================================================

dataset_maestro = dataset_maestro.drop(
    columns=[
        "CONDUCTIVIDAD ELECTRICA",
        "DEMANDA BIOQUIMICA DE OXIGENO (DBO5)",
        "DEMANDA QUIMICA DE OXIGENO (DQO)",
        "FOSFORO TOTAL",
        "NITROGENO TOTAL",
        "OXIGENO DISUELTO (OD)",
        "SOLIDOS SUSPENDIDOS TOTALES",
        "TEMPERATURA",
        "TURBIDEZ",
        "pH"
    ],
    errors="ignore"
)

dataset_maestro = dataset_maestro.merge(
    calidad_mensual,
    on=["Nodo","Anio","Mes"],
    how="left"
)

print("\nIntegración realizada correctamente.")

print("\nDimensiones:")

print(dataset_maestro.shape)

display(dataset_maestro.head())


Integración realizada correctamente.

Dimensiones:
(528, 40)


,Nodo,Fecha_x,Precipitacion_mm,Temp_Max_C,Temp_Min_C,Temp_Media_C,Humedad_Relativa,Velocidad_Viento,Radiacion_Solar,Anio,...,DEMANDA BIOQUIMICA DE OXIGENO (DBO5),DEMANDA QUIMICA DE OXIGENO (DQO),FOSFORO TOTAL,NITROGENO TOTAL,OXIGENO DISUELTO (OD),SOLIDOS SUSPENDIDOS TOTALES,TEMPERATURA,TURBIDEZ,pH,Fecha_y
0,Bogota_Sabana,2015-01-01,2.70,25.30,8.45,18.26,77.88,1.37,17.78,2015,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaT
1,Bogota_Sabana,2015-02-01,2.22,26.14,13.72,19.02,78.83,1.14,17.16,2015,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaT
2,Bogota_Sabana,2015-03-01,5.25,27.56,13.52,19.15,80.28,1.09,16.63,2015,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaT
3,Bogota_Sabana,2015-04-01,6.16,25.50,12.81,19.07,80.32,1.07,16.56,2015,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaT
4,Bogota_Sabana,2015-05-01,3.27,25.52,12.24,18.99,79.57,1.14,16.00,2015,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaT


In [80]:
dataset_maestro = (
    dataset_maestro
    .drop(columns=["Fecha_y"])
    .rename(columns={"Fecha_x": "Fecha"})
)

In [81]:
print(dataset_maestro.shape)
print(dataset_maestro.columns)

(528, 39)
Index(['Nodo', 'Fecha', 'Precipitacion_mm', 'Temp_Max_C', 'Temp_Min_C',
       'Temp_Media_C', 'Humedad_Relativa', 'Velocidad_Viento',
       'Radiacion_Solar', 'Anio', 'Mes', 'ONI', 'Estado_ENSO',
       'VolumenUtilDiarioMasa', 'irca', 'nivel_de_riesgo', 'POBLACION TOTAL',
       'DENSIDAD POBLACIONAL', 'INDICE DE DESEMPENO INSTITUCIONAL',
       'ACCESO A AGUA POTABLE ADECUADO',
       'PORCENTAJE DE LA POBLACION CON ACCESO A METODOS DE SANEAMIENTO ADECUADOS',
       'COBERTURA DE ACUEDUCTO URBANO', 'COBERTURA DE ACUEDUCTO RURAL',
       'COBERTURA DE ALCANTARILLADO URBANO',
       'COBERTURA DE ALCANTARILLADO RURAL', 'CONTINUIDAD DE ACUEDUCTO URBANO',
       'CALIDAD DEL AGUA', 'AGUAS RESIDUALES TRATADAS', 'Nivel_Minimo',
       'CONDUCTIVIDAD ELECTRICA', 'DEMANDA BIOQUIMICA DE OXIGENO (DBO5)',
       'DEMANDA QUIMICA DE OXIGENO (DQO)', 'FOSFORO TOTAL', 'NITROGENO TOTAL',
       'OXIGENO DISUELTO (OD)', 'SOLIDOS SUSPENDIDOS TOTALES', 'TEMPERATURA',
       'TURBIDEZ', 'pH'

In [82]:
print("="*70)
print("VALIDACIÓN FINAL DATASET MAESTRO")
print("="*70)

print("\nDimensiones")
print(dataset_maestro.shape)

print("\nDuplicados Nodo-Fecha")
print(dataset_maestro.duplicated(
    subset=["Nodo","Fecha"]
).sum())

print("\nCobertura temporal")
print(dataset_maestro["Fecha"].min())
print(dataset_maestro["Fecha"].max())

print("\nNodos")
print(dataset_maestro["Nodo"].unique())

print("\nValores nulos")
print(dataset_maestro.isna().sum().sort_values(ascending=False).head(15))

VALIDACIÓN FINAL DATASET MAESTRO

Dimensiones
(528, 39)

Duplicados Nodo-Fecha
0

Cobertura temporal
2015-01-01 00:00:00
2025-12-01 00:00:00

Nodos
['Bogota_Sabana' 'Sopo_Sur' 'Tocancipa_Media' 'Villapinzon_Alta']

Valores nulos
DEMANDA BIOQUIMICA DE OXIGENO (DBO5)    502
NITROGENO TOTAL                         499
TURBIDEZ                                494
INDICE DE DESEMPENO INSTITUCIONAL       480
FOSFORO TOTAL                           479
DEMANDA QUIMICA DE OXIGENO (DQO)        479
CONDUCTIVIDAD ELECTRICA                 478
OXIGENO DISUELTO (OD)                   478
TEMPERATURA                             478
pH                                      478
SOLIDOS SUSPENDIDOS TOTALES             478
Nivel_Minimo                            441
CALIDAD DEL AGUA                        432
CONTINUIDAD DE ACUEDUCTO URBANO         432
AGUAS RESIDUALES TRATADAS               432
dtype: int64


**Análisis Técnico**

**1. Objetivo**

Incorporar al Dataset Maestro la información de calidad del agua proveniente de la Red Nacional de Monitoreo Ambiental, con el propósito de complementar las variables climáticas, oceánicas, hidráulicas, hidrológicas, de gobernanza y percepción mediante indicadores fisicoquímicos representativos del estado de los cuerpos de agua.

Esta integración permite disponer de un conjunto de variables ambientales que describen simultáneamente las condiciones meteorológicas, hidráulicas, hidrológicas y de calidad del recurso hídrico, fortaleciendo la capacidad analítica del Framework para el modelado y la predicción mediante técnicas de Ciencia de Datos.

**2. Descripción del proceso**

La capa de Calidad del Agua se construyó a partir de registros históricos de monitoreo ambiental.
* **Filtro Espacial:** Inicialmente, la fuente contenía **10,875 registros** correspondientes a 68 propiedades de calidad del agua (cobertura temporal 2005–2024). Dado que el Framework se limita a la cuenca de estudio, se excluyeron los municipios que no pertenecen al ámbito geográfico del proyecto (`Cota`, `Soacha`, `Girardot`, `El Colegio` y `Tocaima`), conservando únicamente los registros de `Bogotá D.C.`, `Chía`, `Tocancipá` y `Villapinzón`.
* **Homologación de Nodos:** Se mapearon los municipios seleccionados hacia la nomenclatura oficial del Dataset Maestro:

| Municipio original | Nodo Framework (Destino) |
| :--- | :--- |
| `Bogotá D.C.` | **Bogota_Sabana** |
| `Chía` | **Bogota_Sabana** |
| `Tocancipá` | **Tocancipa_Media** |
| `Villapinzón` | **Villapinzon_Alta** |

**3. Selección de variables**

De los 68 parámetros fisicoquímicos iniciales, se seleccionaron los **10 atributos de mayor relevancia técnica** y densidad temporal de muestreo:

* Conductividad eléctrica
* Demanda Química de Oxígeno (DQO)
* Demanda Bioquímica de Oxígeno ($DBO_5$)
* Oxígeno Disuelto (OD)
* Temperatura del agua
* pH
* Turbidez
* Fósforo Total
* Nitrógeno Total
* Sólidos Suspendidos Totales (SST)

**4. Transformación temporal**

La estructura transaccional original (formato longitudinal) requirió un preprocesamiento sistemático antes de la fusión:
* **Agregación:** Se agruparon las observaciones por Nodo, Año, Mes y propiedad, calculando el valor promedio mensual.
* **Pivotado (Long-to-Wide):** Se reestructuraron los datos para pasar de un formato de filas transaccionales a un formato matricial amplio, generando una columna única para cada parámetro.

**5. Resultado del preprocesamiento:**

Se consolidó una matriz temporalmente alineada de **137 registros y 13 columnas**, optimizada para la integración de datos.

**6. Integración con el Dataset Maestro**
La fusión se ejecutó aplicando un **`LEFT JOIN`** utilizando como claves combinadas de unión:

$$\text{Llaves de unión: } \{\text{Nodo, Año, Mes}\}$$

Esta operación prioriza la permanencia de todos los registros preexistentes del Dataset Maestro, anexando las propiedades físico-químicas de calidad del agua únicamente en los periodos y nodos donde se ejecutaron campañas de monitoreo efectivas.

**7. Resultados de la validación**

La auditoría de calidad posterior al proceso de integración confirmó los siguientes puntos de control:

* **Consistencia estructural:** El número total de registros del Dataset Maestro permaneció inalterado (528 registros), confirmando que el proceso no indujo duplicaciones accidentales de filas.
* **Alineación espacial y temporal:** Las mediciones del laboratorio fueron asignadas con precisión matemática a sus correspondientes nodos y meses.

**8. Justificación de Datos Faltantes (NaN)**

La presencia de valores nulos observada es representativa de la dinámica de captura de este dominio científico y responde a los siguientes factores de campo:
* **Muestreo Discontinuo:** A diferencia de las variables climáticas de registro continuo diario, las variables de calidad del agua se miden de forma periódica en campañas de muestreo específicas (no mensuales).
* **Ausencia de Estaciones en Sopo_Sur:** El nodo **Sopo_Sur** carece de datos debido a que la red oficial no dispone de estaciones físicas de monitoreo activas en ese tramo de control durante el periodo evaluado.
* **Límite Temporal (Año 2025):** Las series históricas de la fuente oficial de calidad del agua finalizan en el año 2024, razón por la cual los registros correspondientes al 2025 permanecen nulos.

**9. Aporte al Framework**

La incorporación de esta capa representa la última etapa de integración temática del Dataset Maestro.

Mientras las dimensiones climática, oceánica, hidráulica e hidrológica describen los elementos físicos y de disponibilidad cuantitativa del recurso, la dimensión de **Calidad del Agua** añade la perspectiva cualitativa y sanitaria del recurso hídrico. Esta sinergia de datos consolida una de las mayores fortalezas del Framework, ya que permite entrenar algoritmos de Inteligencia Artificial capaces de correlacionar la variabilidad ambiental multiescala con el estado y la aptitud del recurso.

**10 Conclusión técnica**

* **Hito del Framework:** Con la integración de la capa de Calidad del Agua concluye satisfactoriamente el diseño y la construcción del **Dataset Maestro Integrado**.

Este activo analítico de siete capas temáticas constituye una base de datos estandarizada, espacialmente coherente, temporalmente unificada y técnicamente sólida. A partir de este momento, el dataset está listo para servir como el núcleo de entrada de las fases posteriores de **Ingeniería de Características** (*Feature Engineering*), **Modelamiento Predictivo** con algoritmos de Machine Learning y simulación de escenarios de gestión del agua.



## **M5 Construcción del Dataset Maestro**

In [83]:
dataset_maestro.to_parquet(
    "Dataset_Maestro_Framework_v1.parquet",
    index=False
)

In [84]:
dataset_maestro.to_csv(
    "Dataset_Maestro_Framework_v1.csv",
    index=False,
    encoding="utf-8-sig"
)

In [86]:
from contextlib import redirect_stdout
from datetime import datetime

archivo = "Dataset_Maestro_Framework_v1.txt"

with open(archivo, "w", encoding="utf-8") as f:

    f.write("="*80 + "\n")
    f.write("FRAMEWORK DE GESTIÓN HÍDRICA\n")
    f.write("RESUMEN DEL DATASET MAESTRO\n")
    f.write("="*80 + "\n\n")

    f.write(f"Fecha de generación : {datetime.now()}\n")
    f.write("Versión             : 1.0\n")
    f.write("Módulo              : Integración del Dataset Maestro\n\n")

    f.write("="*80 + "\n")
    f.write("DIMENSIONES\n")
    f.write("="*80 + "\n")
    f.write(f"Registros : {dataset_maestro.shape[0]}\n")
    f.write(f"Columnas  : {dataset_maestro.shape[1]}\n\n")

    f.write("="*80 + "\n")
    f.write("TIPOS DE DATOS\n")
    f.write("="*80 + "\n")

    with redirect_stdout(f):
        dataset_maestro.info()

    f.write("\n")

    f.write("="*80 + "\n")
    f.write("ESTADÍSTICAS DESCRIPTIVAS\n")
    f.write("="*80 + "\n")

    f.write(dataset_maestro.describe(include="all").to_string())

    f.write("\n\n")

    f.write("="*80 + "\n")
    f.write("VALORES NULOS\n")
    f.write("="*80 + "\n")

    f.write(dataset_maestro.isnull().sum().to_string())

    f.write("\n\n")

    f.write("="*80 + "\n")
    f.write("COBERTURA TEMPORAL\n")
    f.write("="*80 + "\n")

    f.write(f"Fecha inicial : {dataset_maestro['Fecha'].min()}\n")
    f.write(f"Fecha final   : {dataset_maestro['Fecha'].max()}\n")

    f.write("\n\n")

    f.write("="*80 + "\n")
    f.write("NODOS\n")
    f.write("="*80 + "\n")

    for nodo in sorted(dataset_maestro["Nodo"].unique()):
        f.write(f"- {nodo}\n")

print(f"Archivo generado: {archivo}")

Archivo generado: Dataset_Maestro_Framework_v1.txt
